stitchdata/docs

_integration-schemas/facebook-ads/adcreative.md
This PR removes the `use_page_actor_override` field from Facebook Ad's `adcreative` schema listing, as it is no longer supported.
=> Remove `use_page_actor_override` from adcreative

_saas-integrations/google-adwords/google-adwords-latest.md
This PR adds info to the AdWords setup requirements about linking MCC accounts prior to connecting Stitch.
This step is necessary because AdWords API access is not available on advertiser accounts. Access is only granted to managed accounts, making the connection necessary to extract data via Stitch.
=> Adwords: MCC Account Requirement

Gemfile, _config.yml, _includes/layout/head.html, _layouts/default.html, _layouts/page.html
This PR adds the `install-cache` gem to the site. This plugin caches include files during builds to reduce the overall build time.
Repo is here: https://github.com/benbalter/jekyll-include-cache
=> Install include-cache gem

_saas-integrations/zuora.md
Zuora now supports sandbox accounts.
Steps for selecting the account level during setup still need to be added.
=> Remove Zuora non-sandbox prerequisite

_includes/replication/databases/extraction-queries.html
This PR updates the extraction queries template to reflect the fact that MongoDB integrations don't currently support Full Table Replication.
=> Remove Full Table Replication from Mongo

_account-security/understanding-stitch-billing-replicated-rows.md
Pausing an integration does not pause the loading process, though it does pause the extraction process. This is a pretty significant caveat and the language added should clarify this behavior.
Added: Note that pausing an integration will prevent the extraction of additional records, while loading will continue for any records that have already been extracted.
=> Clarify Pausing Behavior re: loading

_integration-schemas/freshdesk/contacts.md
This PR comments out the Freshdesk `contacts` table.
As per [this PR](https://github.com/singer-io/tap-freshdesk/pull/12), we aren't currently supporting replication of this table.
=> Freshdesk: Hide unsupported `contacts` table

_troubleshooting/destinations/redshift-dependent-view-errors.md
This PR improves the documentation for troubleshooting Redshift view dependency errors:
- Added a more straightforward and user-friendly dependent view query
- Added instructions for querying the view to locate dependencies
=> Improve Redshift view dependency doc

_destinations/snowflake.md, _destinations/snowflake/setup/connecting-snowflake.md
This PR adds the `AUTO_SUSPEND` parameter to the creation command section of the Snowflake setup doc. If left undefined, the value will default to `NULL`, meaning the warehouse will **never** suspend (even when inactive) and credits will be rapidly consumed.
=> Add AUTO_SUSPEND to Snowflake setup

_saas-integrations/salesforce/salesforce-latest.md
This PR adds clarification to the IP whitelisting section of the Salesforce documentation. In Salesforce, the UI asks for an IP range and not single IP addresses. 
To add exact IPs to the trusted list, users must enter the same IP in the Start and End fields. This changes adds that explicit instruction.
=> Salesforce: Update IP whitelisting instructions

_integration-schemas/facebook-ads/adcreative.md, _integration-schemas/facebook-ads/ads.md, _integration-schemas/facebook-ads/ads_insights.md, _integration-schemas/facebook-ads/ads_insights_age_and_gender.md, _integration-schemas/facebook-ads/ads_insights_country.md, _integration-schemas/facebook-ads/ads_insights_platform_and_device.md, _integration-schemas/facebook-ads/adsets.md, _integration-schemas/facebook-ads/campaigns.md, _saas-integrations/facebook-ads/facebook-ads-latest.md
This PR:
- Adds the new `include deleted data for campaigns, adsets, and ads` field to the Facebook Ads setup instructions
- Adds Core Object and Insight terms to differentiate between the table types in the integration
=> Add deleted data option to FB Ads

_includes/integrations/webhooks/webhook-replication.html
This PR fixes a minor display issue in the webhook docs.
A variable was missing the correct prefix (`system-column.`), which caused Jekyll to output nothing instead of the column name.
=> Correct system column variable

_saas-integrations/harvest/harvest-latest.md
This PR corrects the Harvest integration's status from `premium` to `free`.
=> Update Harvest status

_integration-schemas/hubspot/deals.md
When helping a customer, I noticed that the endpoint previously mentioned isn't the endpoint we actually use.
See: https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/__init__.py#L76
and: https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/__init__.py#L449
=> HubSpot: Update endpoint for deals

_database-integrations/mongodb.md
"Panoply" was accidentally typed here instead of Redshift.
=> Change Panoply to Redshift

_includes/replication/reset-rep-keys.html
We should update this to more strongly suggest to users that their destination tables will be dropped and re-created when they reset keys in a db integration.
=> update reset replication key consideration

_integration-schemas/hubspot/deal_pipelines.md
This will add the deal_pipelines table to the schema documention for HubSpot.
https://github.com/singer-io/tap-hubspot/commit/da1b444de55186ddd030f73c5a6b31e7204900fc
This list excludes the undocumented `staticDefault` field: https://github.com/singer-io/tap-hubspot/pull/54/commits/804c6ec4171b298e064a6c9690f270243d4f4130
- name: “staticDefault”
type: “Boolean”
description: “This field is not listed in HubSpot's API documentation, but is returned in results from the `/deals/v1/pipelines`
endpoint.”
=> HubSpot: Add `deal_pipelines` table

_saas-integrations/mixpanel.md
The response from [Mixpanel API](https://mixpanel.com/help/reference/exporting-raw-data#export-api-reference) includes an object that includes all of the attributes of the given event. This results in flattening of records.
See:
"One event per line, sorted by increasing timestamp. *Each line is a valid JSON object* although the return itself is valid JSON but instead JSONL."
=> Mixpanel: Export and Engage have nested data

_saas-integrations/adroll.md
This PR updates the links to AdRoll’s API documentation to reflect their URL change.
=> Update links for AdRoll tables

_saas-integrations/mixpanel.md
We listed the field as _sdc_record_hash, though this field is loaded as _rjm_record_hash.
=> Update Schema of mixpanel_export

_integration-schemas/google-adwords/keywordless_query_report.md
We are adding the Keywordless Query Report to the Google AdWords integration as a new integration type. This adds it as one of the reports in the AdWords schema.
=> Add Keywordless Query Report to AdWords

_destinations/bigquery/switching-location-of-google-bigquery.md
This PR adds instructions for deleting staging buckets to the destination switching guide for BigQuery.
=> BigQuery: Instructions for deleting buckets

_integration-schemas/hubspot/v01-03-2017/workflows.md
This PR corrects the `version` value of the HubSpot `workflows` table in release `01-03-2017`.
=> HubSpot: Correct `workflows` version

_database-integrations/magento.md, _includes/integrations/databases/setup/database-integration-settings.html, _includes/notifications/support-beta-singer-notice.html
This PR adds a parameter named `setup-name` to integrations that don’t have a dedicated UI in Stitch, but are still supported.
Notifications and instructions will use the name of the dedicated integration to reduce confusion. Ex: Magento databases can be connected using the MySQL integration.
=> Use setup-name

_integration-schemas/referral-saasquatch/users.md
This PR adds the `accountId` field as a primary key to the Referral SaaSquatch`users` stream due to [#4](https://github.com/singer-io/tap-referral-saasquatch/pull/4)
=> Ref SaaSquatch: Add accountId as PK to users table

_integration-schemas/hubspot/contacts_by_company.md
This PR corrects a link in the HubSpot 2.0 `contacts_by_company` table schema file.
=> Fix link to github schema for contacts_by_company

_account-security/billing-faq.md, _includes/integrations/shared-setup/initial-syncs.html
This PR updates the documentation to reflect that FHDL (free historical data loads) begin **after** an integration begins to replicate data. 
This behavior is the same way trials begin: the 14 days for a trial begin only when a destination has been connected and data starts to replicate.
=> Correct FHDL start behavior

_database-integrations/mariadb.md, _includes/integrations/databases/setup/binlog/vanilla-mysql.html
This PR adds binlog setup instructions for MySQL-backed MariaDB.
=> Binlog instructions for MariaDB

_data/taps/versions/hubspot.yml, _includes/notifications/integration-version-deprecation-list.html, _pages/announcements.md
Adding HubSpot 1.0 deprecation date to provide 90 days from formal communication.
=> HubSpot 1.0 deprecation

_data/taps/versions/zuora.yml
Pushing the Zuora deprecation date to September 1 to provide 90 days from formal communication.
=> Update Zuora v15-10-2015 deprecation date

_destinations/amazon-s3/setup/connecting-amazon-s3.md
This PR updates the copy in the **Note** box for the S3 webhook setup instructions. This is an Enterprise-only feature. Customers who are interested should contact Stitch Sales for more info.
=> Amazon S3: Add Ent CTA to webhook setup

_destinations/destination-integration-incompatibility.md, _includes/destinations/destination-level-incompatibility.html, _includes/destinations/full-incompatibility-matrix.html, _includes/integrations/saas/ads-append-only-replication.html, _saas-integrations/google-adwords/google-adwords-latest.md, _saas-integrations/hubspot/hubspot-latest.md
This PR:
- Makes HubSpot sometimes incompatible with Postgres
- Updates the Google AdWords query to partition by `day` and `customerid`
- Adds a section to the Google AdWords doc about money field values
=> Minor integration updates

_account-security/stitch-security.md
This PR fixes a minor typo in the Security FAQ.
=> Fix typo in Security FAQ

_destinations/redshift/connecting-redshift-ssh-tunnel.md, _includes/destinations/setup/postgresql-create-user-intro.html, _includes/destinations/setup/redshift-postgres-database-users.html, _includes/destinations/setup/redshift-postgres-permissions.html, _includes/destinations/setup/redshift-postgres-transfer-schema-ownership.html, _includes/destinations/setup/setup-wrapup.html, _layouts/destination-setup-guide.html
This PR:
- Adds clarification around the requirements for naming VPC Security Groups. SG names within the same VPC must be unique.
- Adds a note about the reason for a publicly available bastion
- Fixes capitalization in a few headings
=> Corrections to Redshift SSH

_saas-integrations/quickbooks.md
This PR adds a link to the QuickBooks site to the QB docs, as per a support request from QuickBooks’s marketing team.
=> Add link to QuickBooks site

_saas-integrations/pipedrive.md
This PR fixes an issue where the Pipedrive integration wasn’t display in the sidenav or on any of the integration category pages.
To display in the sidenav/on category pages, the following Frontmatter parameters must be present:
```yaml
input: true  # must be true
certified: true/false
```
`certified` may be `true` or `false` - the variable just has to be present and not null.
=> Make Pipedrive a community integration

_saas-integrations/mixpanel.md
This PR fixes the display of a callout box in the Historical sync section of the Mixpanel docs.
=> Mixpanel: Fix display of Start Date info

_integration-schemas/google-adwords/ad_performance_report.md
This PR fixes the Primary Key for Google AdWords’ `ad_performance_report` table.
=> AdWords: Fix PK for ad_performance_report

_data/taps/versions/marketo.yml
Adding Marketo 1.0 deprecation date to provide 90 days from formal communication.
=> Marketo 1.0 deprecation

_connect-files/api/documentation/api-introduction.md
This PR fixes a typo in the Import API introduction.
=> Typo in Import API introduction

_connect-files/api/objects/accounts/create-an-account.md, _data/connect/general.yml
This PR does the following in the Connect docs:
- Updates the `start_date` example to use midnight as the time since that's what the regex validation requires
- Removed the access token from the header on the account `POST` example since it's not required to post an account
=> Connect: Correct start_date format and POST account example

_saas-integrations/shopify.md
This PR corrects the Replication Method for Shopify's `order_refunds` table.
=> Shopify: Update order_refunds Replication Method

_includes/integrations/templates/schemas/table-schemas.html
Characters other than alphanumeric, spaces, or hyphens break anchor links in expanding headings. This fixes that and replaces those characters with hyphens.
=> Remove characters from table schema links

_data/connect/general.yml
10 is not a valid frequency option, and 1 is only supported for database integrations.
=> Connect: Remove 1 and 10 as frequency options

_integration-schemas/zendesk/ticket_forms.md
I recently added the `ticket_forms` stream to tap-zendesk.  This is the corresponding documentation PR for it.  
A few questions:  
- Do we include foreign key distinctions for streams that the tap doesn't currently support?  (e.g. the `restricted_brand_ids` attribute)
- When I added the `ticket_forms` stream, I bumped the version to 1.1.0.  Should this be reflected in the `version` in this stream's doc or does that refer to a different version?
Singer PR: https://github.com/singer-io/tap-zendesk/pull/15
=> Zendesk v1: Add ticket_forms stream

_includes/destinations/overviews/replication-process.html, _includes/replication/append-only-replication-example.html
The original does not take into account the fact that during append-only replication, records which have a replication key value greater than or equal to the previous bookmark will also be replicated.
=> Append-Only example: Rep Key inclusivity with updated_at

_data-structure/nested-data-structures-row-count-impact.md, _data/taps/versions/facebook-ads.yml, _data/taps/versions/google-adwords.yml, _data/taps/versions/google-analytics-adwords.yml, _data/taps/versions/hubspot.yml, _data/taps/versions/marketo.yml, _data/taps/versions/mysql.yml, _data/taps/versions/postgres.yml, _data/taps/versions/salesforce.yml, _data/taps/versions/version-template.yml, _data/taps/versions/zendesk.yml, _data/taps/versions/zuora.yml, _data/urls.yaml, _includes/integrations/templates/schemas/table-schemas.html, _includes/notifications/integration-deprecation-notice.html, _layouts/singer.html
This PR fixes a few small, but annoying/confusing things:
- **Nested data flattening:** The info box in this article now uses a `forloop` to identify destinations that don't support nested structures (`nested-structure-support: false`) and only display the names of those destinations. This is in response to a support convo where a user noted that we incorrectly listed Snowflake, as nested data isn't flattened but stored as `VARIANT`.
- **Object naming in integration Table Schema sections**: A user pointed out that we display the Quickbooks schema as all lowercase, but in Postgres there are mixed-case object names. While this is expected behavior, not noting this in the docs lead to some confusion for the user.
For the time being, I added a notice to this section that calls out object …
=> Miscellaneous fixes

_connect-files/api/objects/sessions/create-a-session.md, _connect-files/api/objects/sessions/sessions-object.md, _data/connect/api.yml, _data/connect/general.yml
This PR:
* Updates the Connect API `/sessions/ephemeral` documentation to clarify when ephemeral tokens expire
* Updates the Connect API `/sessions/ephemeral` documentation to clarify how long sessions are valid after the ephemeral token is used to create a session
* Updates the Connect JS documentation to clarify when ephemeral tokens expire
* Updates the Connect JS documentation to clarify how long sessions are valid after the ephemeral token is used to create a session
=> Connect: Add more details about the ephemeral token and session token expiration

_data/taps/versions/zendesk.yml
Added a deprecation date of Nov 5 for older Zendesk integration.
=> Added zendesk (v15-10-2015) deprecation date

_database-integrations/postgres/amazon-rds/postgresql-amazon-rds-overview.md, _database-integrations/postgres/amazon-rds/v1/postgresql-amazon-rds-v1.md, _database-integrations/postgres/cloudsql/v1/google-cloudsql-postgresql-v1.md, _database-integrations/postgres/vanilla/v1/postgres-v1.md, _database-integrations/postgres/vanilla/vanilla-postgres-overview.md, _includes/integrations/databases/setup/binlog/configure-server-settings-intro.html, _includes/notifications/postgres-binlog-limitations.html
This PR adds info about logical replication limitations to the overview and setup docs for vanilla Postgres and Postgres RDS.
The limitations:
- The Singer PostgreSQL tap only supports logical replication for Postgres databases running 9.4.x - 9.9.x.
Version 10 renames some of the functions used for logical replication. We're working on adding this feature to the tap.
- Only master instances can use logical replication. Log-based replication will only work on master instances due to a feature gap in PostgreSQL 10. [Based on their forums, PostgreSQL](https://commitfest.postgresql.org/12/788/) is working on adding support for using logical replication on a read replica to a future version.
=> PostgreSQL v1: Logical replication limitations

_integration-schemas/google-adwords/accounts.md, _integration-schemas/google-adwords/ad_groups.md, _integration-schemas/google-adwords/ads.md, _integration-schemas/google-adwords/campaigns.md, _saas-integrations/google-adwords/google-adwords-latest.md
Tap-adwords just got an update to its API version to the latest v201806. Although the links to google's docs here redirect to that version, I thought I'd make a PR to make them explicit.
=> Update references to adwords docs to api version v201806

_data/taps/versions/zendesk.yml, _integration-schemas/zendesk/foreign-keys.md, _integration-schemas/zendesk/satisfaction_ratings.md, _integration-schemas/zendesk/ticket_comments.md
This PR:
- Adds documentation for the new `satisfaction_ratings` table (https://github.com/singer-io/tap-zendesk/pull/17)
- Adds documentation for the new `ticket_comments` table (https://github.com/singer-io/tap-zendesk/pull/17)
- Updates the foreign keys for Zendesk
- Updates Zendesk’s changelog
=> Zendesk/v1: Add `satisfaction_ratings` & `ticket_comments`

_connect-files/api/objects/form-properties/sources/doubleclick-campaign-manager-object.md, _data/connect/api.yml, _data/sidebars/connect.yml
This PR adds the DoubleClick Campaign Manager report card to Connect.
=> DoubleClick Campaign Manager - add to Connect

_database-integrations/postgres/amazon-rds/v1/postgresql-amazon-rds-v1.md, _database-integrations/postgres/vanilla/v1/postgres-v1.md, _includes/integrations/databases/setup/binlog/postgres-replication-slot.html
This PR:
- Removes the version restriction for v10 + logical replication (https://github.com/singer-io/tap-postgres/pull/15)
- Updates the setup steps for creating replication slots (https://github.com/singer-io/tap-postgres/pull/18)
=> Postgres: v10 & replication slots

_saas-integrations/xero/v19-10-2016/xero-v19-10-2016.md
This PR updates the release status of the 19-10-2016 version of Xero to `deprecated`.
=> Xero/Change v19-10-2016 status

_integration-schemas/google-adwords/account_performance_report.md
Corrects the link for the custom fields column attributes
=> AdWords: Fix link in `account_performance_report`

_includes/notifications/postgres-binlog-limitations.html
removes indication that postgresql 10 is not supported, as this support has been added.
=> Postgres/v1: Remove v10 notice from binlog setup instructions

_saas-integrations/amplitude/v1/amplitude-v1.md
This PR updates the integration’s Availability to correctly be `Free`.
=> Amplitude/v1 - Free

_connect-content/connect-api.md, _connect-files/api/objects/form-properties/sources/postgresql-object.md, _data/connect/general.yml, _data/ui/database-integration-settings/postgres.yml, _data/urls.yaml, _includes/connect/api-form-properties.html, _troubleshooting/data-discrepancies/database-integration-table-name-collisions.md
This PR:
- Adds documentation for the new **Include schema names in destination tables** setting for PostgreSQL-backed integrations
- Adds a troubleshooting guide for database integration table name collisions
=> Postgres/v1 - schema/table name setting

_saas-integrations/google-analytics.md
Adds the word `recent` to the pre-requisites.
"The user creating the integration has at least [Read & Analyze permissions](https://support.google.com/analytics/answer/2884495?hl=en) and that there's data in the account." --> "The user creating the integration has at least [Read & Analyze permissions](https://support.google.com/analytics/answer/2884495?hl=en) and that there's recent data in the account."
Historical data beyond 30 days in the past will not be sufficient for authorizing the connection, so this helps to clarify that necessity a bit further
=> Google Analytics - Clarify 'recent' data

_replication/syncing-data.md
We do not select columns for replication by default for SaaS integrations.
=> Change default behavior for column selection

_data-structure/querying-append-only-tables.md, _data/sidebars/stitchnav.yml
This PR updates the append-only query example to include the `_sdc_batched_at` column, which adds another layer of uniqueness to query results.
=> Append only query update

_integration-schemas/outbrain/campaigns.md
This PR changes the Outbrain `campaigns` table's Replication Method to Full Table.
=> Outbrain: Correct `campaigns` Replication Method

_connect-files/api/objects/form-properties/sources/saas/marketobulk-object.md
This PR removes the `identity` attribute from the `marketobulk` Connect source form property. This attribute isn't used in this version of the integration.
=> Marketo: Update report card

_saas-integrations/netsuite/netsuite-latest.md
This PR adds in two steps that were accidentally removed from the NetSuite docs in #177.
=> NetSuite: Add setup steps back in

_integration-schemas/zendesk/foreign-keys.md, _integration-schemas/zendesk/sla_policies.md, _saas-integrations/zendesk/zendesk-latest.md
This PR adds documentation for the new `sla_policies` table. (https://github.com/singer-io/tap-zendesk/pull/21)
It also adds info about replicating the following types of data:
- `ticket_forms`
- `sla_policies`
- `users` custom fields
- `organizations` custom fields
=> Zendesk/v1: Add sla_policies table & replication requirements

_destinations/postgresql/setup/google-cloudsql-postgres.md
This PR removes the SSL callout from the GCS Postgres destination setup docs. Stitch doesn’t currently support SSL connections to GCS.
=> GCS Postgres destination - Remove SSL callout

_integration-schemas/hubspot/campaigns.md, _integration-schemas/hubspot/companies.md, _integration-schemas/hubspot/contact_lists.md, _integration-schemas/hubspot/contacts.md, _integration-schemas/hubspot/deal_pipelines.md, _integration-schemas/hubspot/deals.md, _integration-schemas/hubspot/email_events.md, _integration-schemas/hubspot/engagements.md, _integration-schemas/hubspot/forms.md, _integration-schemas/hubspot/owners.md, _integration-schemas/hubspot/subscription_changes.md, _integration-schemas/hubspot/workflows.md, _saas-integrations/hubspot/v2/hubspot-v2.md
This PR updates the HubSpot v2 docs to include info about the permissions required to replicate `email_events`. As of now, Super Admin permissions are required by HubSpot to access this data via the API.
=> HubSpot/v2 - Email events permissions

_saas-integrations/bing-ads/v1/bing-ads-v1.md, _saas-integrations/bing-ads/v2/bing-ads-v2.md
This PR adds info about Bing Ads’ retention period to the documentation. Retention periods can affect the amount of historical data Stitch can replicate from Bing Ads, depending on the report type: https://docs.microsoft.com/en-us/bingads/guides/report-data-retention-time-periods?view=bingads-12
=> Bing Ads/v1 - Add retention period info

_saas-integrations/bing-ads/v2/bing-ads-v2.md
This PR fixes a typo in a callout in the Bing Ads docs.
=> Fix notice content variable in Bing Ads

_integration-schemas/github/comments.md, _integration-schemas/github/foreign-keys.md, _integration-schemas/github/review_comments.md, _integration-schemas/github/reviews.md
This PR adds documentation for the new `comments` and `review_comments` tables in the GitHub integration. (https://github.com/singer-io/tap-github/pull/30)
=> GitHub/v1 - Add comments and review_comments tables

_saas-integrations/pipedrive/pipedrive-latest.md
Pipedrive removed the `goals` endpoint, and the stream has been removed from the tap in [#44](https://github.com/singer-io/tap-pipedrive/pull/44).  
This PR removes the docs for the `goals` stream
=> Pipedrive: Remove goals stream

_integration-schemas/zendesk/foreign-keys.md, _integration-schemas/zendesk/ticket_comments.md
The `ticket_id` was [added](https://github.com/singer-io/tap-zendesk/pull/22) to the `ticket_comments` stream.  
This PR adds it to the docs.
=> Zendesk: Add `ticket_id` to `ticket_comments` table

_integration-schemas/facebook-ads/ads_insights.md, _integration-schemas/facebook-ads/ads_insights_age_and_gender.md, _integration-schemas/facebook-ads/ads_insights_country.md, _integration-schemas/facebook-ads/ads_insights_platform_and_device.md, _integration-schemas/facebook-ads/ads_insights_region.md
tap-facebook was recently updated to use v3.2 of facebook's `facebook_business` sdk, (see [this PR](https://github.com/singer-io/tap-facebook/pull/51))
Part of the upgrade meant that `total_action_value` was removed from the ads_insights streams.
This PR removes that value from those schemas' docs.
=> remove total_action_value from facebook insights schemas

_connect-files/api/objects/form-properties/destinations/postgresql-object.md, _data/connect/common/destination-forms.yaml, _data/ui/destination-settings-page.yml
This PR adds documentation for user-provided SSL certificates for PostgreSQL destinations.
=> Add docs about Postgres SSL certs

_destinations/bigquery/switching-location-of-google-bigquery.md, _destinations/bigquery/understanding-stitch-impact-on-bigquery-costs.md, _destinations/redshift/apply-encodings-sort-dist-keys-redshift.md, _destinations/redshift/remove-database-integration-columns-redshift.md, _destinations/switching-stitch-destinations.md
This PR moves some destination guides that got missed during the overhaul for Azure over to the new template.
=> Move destination guides to new template

_destinations/microsoft-azure.md
This changes the status of the Azure SQL DW destination to `Open Beta`.
=> Switch Azure SQL DW to Open Beta

_data/dataloading/bigquery.yml
This PR updates the decimal info for the BigQuery loading guide. Decimal data will now be loaded as data type [`NUMERIC`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric-type).
=> BigQuery: Decimals load as NUMERIC

_includes/notifications/integration-deprecation-notice.html, _saas-integrations/stripe/v1/stripe-v1.md, _saas-integrations/stripe/v27-02-2015/stripe-v27-02-2015.md
This PR makes Stripe v1 the default, and deprecates the previous version of the integration.
=> Stripe/v1 - Release

_database-integrations/mssql/azure/msazure.md, _database-integrations/mssql/microsoft-sql-server.md
This PR corrects the value for`log-based-replication-master-instance` for MSSQL and Azure sources. This is not currently supported.
=> Correct log-rep for MSSQL databases

_database-integrations/mongo/mongodb.md
This PR clarifies the Atlas requirement for MongoDB integrations. Users must be on a paid plan with a dedicated cluster.
=> Update MongoDB with info on dedicated clusters

_includes/replication/templates/data-types/common-data-types.html
This fixes the table for common data types. It was broken due to removing a data type in #235. This table will now work no matter how many data types are listed.
=> Fix data type table formatting

_saas-integrations/github/github-latest.md
Unless you include the "username/" before the repository name you'll get a permissions error on first sync.
=> GitHub/v1: Update repository name instructions

_data/destinations/reference/amazon-s3.yml, _data/destinations/reference/bigquery.yml, _data/destinations/reference/defaults.yml, _data/destinations/reference/microsoft-azure.yml, _data/destinations/reference/panoply.yml, _data/destinations/reference/postgres.yml, _data/destinations/reference/snowflake.yml, _destinations/bigquery/connecting-google-bigquery-to-stitch.md
This PR adds a list of supported regions for the BigQuery destination. Stitch now supports the following BQ regions:
- United States (US)
- European Union (EU)
- London (europe-west2)
- Singapore (asia-southeast)
- Tokyo (asia-northeast)
- Sydney (australia-southeast)
=> BigQuery: Add supported regions

_database-integrations/postgres/cloudsql/v1/google-cloudsql-postgresql-v1.md
This PR removes the mention of modifying `standby_*` parameters in Google CloudSQL PostgreSQL, as Google doesn’t currently allow users to modify these settings.
=> CloudSQL PG: Remove `standby` parameters

_database-integrations/mysql/aurora-rds/amazon-aurora.md
log_slave_updates can't be modified for aurora instances. this pr clarifies why binlog cannot be used with a replica
=> Aurora MySQL RDS: Clarify why binlog isn't supported on replicas

_data/destinations/reference/microsoft-azure.yml, _destinations/microsoft-azure.md
This PR moves the Azure SQL Data Warehouse destination from `open beta` to `released`.
=> Move Azure SQL DW to released

_integration-schemas/salesforce-marketing-cloud/v1/content_area.md, _integration-schemas/salesforce-marketing-cloud/v1/list.md, _integration-schemas/salesforce-marketing-cloud/v1/send.md, _integration-schemas/salesforce-marketing-cloud/v1/subscriber.md
This PR fixes some issues with the tables for the Salesforce Marketing Cloud integration.
=> Fix SFMC table names

_connect-files/api/documentation/api-authentication.md
This was an incorrect hyperlink before.
=> Update link to Create Account endpoint

_integration-schemas/intercom/users.md
We use the list-users endpoint, not the scroll endpoint.
=> Update intercom users API link

_includes/integrations/databases/setup/db-users/mysql.html
Column level permissions are not supported for use with log-based replication. This adds a note to make users aware.
=> Update User Permissions re: column-permissions

_includes/layout/inline_image.html
This PR fixes the display of inline images. The spacing was making Jekyll render it as code.
=> Fix display of inline images

_replication/replication-methods/log-based-incremental-replication.md, _troubleshooting/data-discrepancies/data-discrepancy-troubleshooting-guide.md
Changes: 
- reflect that historical syncs with a PK will always try to bookmark against that PK
- encourage users to wait until syncs are complete to analyze data discrepancies
=> Update docs for new historical sync strategy

_integration-schemas/facebook-ads/ads_insights_dma.json, _integration-schemas/facebook-ads/foreign-keys.md
This PR adds docs for the new `ads_insights_dma` table for the Facebook Ads integration.
=> add ads_insights_dma breakdown for Facebook Ads

_integration-schemas/jira/users.md
This PR removes 4 fields (groups, applicationRoles, locale, expand) which are not supported by the endpoint used to retrieve users (https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-group-member-get) and are consequently unavailable through stitch currently.
=> Update schema of users for accuracy

_connect-files/api/objects/replication-jobs/start-a-replication-job-v4.md
Provide clarification that the replication job limit is on a source basis, not an account wide basis
=> Clarify job start limit in documentation

_database-integrations/oracle/oracle-rds/oracle-rds-v1.md, _database-integrations/oracle/oracle-v1.md, _includes/integrations/databases/setup/binlog/configure-server-settings-intro.html
Updated Oracle RDS page to be in line with vanilla Oracle page
Updated link to "Datatypes" on both pages
=> Updated Oracle RDS and assoc. links

_data/taps/extraction/data-types/mssql/specific.yml, _data/taps/extraction/data-types/mssql/v1.yml
This updates the docs to include three newly supported data types for v1 of the MSSQL integration: `datetime2`, `datetimeoffset`, and `smalldatetime`.
https://github.com/stitchdata/tap-mssql/pull/49
=> MSSQL/v1 - New date-time data types

_replication/replication-methods/key-based-incremental-replication.md
=> Correct spelling on Key-based Incremental Replication Stitch Docs page

_data/taps/versions/netsuite.yml
This changes the deprecation date for 10-15-2015 to reflect the actual deprecation date rather than the integration's sunset date.
=> Update NetSuite Deprecation

_data/taps/extraction/data-types/mssql/specific.yml, _data/taps/extraction/data-types/mssql/v1.yml
This PR adds the `MONEY` and `SMALLMONEY` data types to Microsoft SQL Server-based integrations.
=> MSSQL/Add MONEY and SMALLMONEY data type support

_developer-files/connect/api/objects/form-properties/sources/saas/shopify-object.md
Added the `results_per_page` property to the connect form. I commented it out because this isn't a property that the user will touch. It's only there for the sources team to adjust for a client if they are having trouble downloading the normal amount of results at a time.
=> Shopify/v1 - Results per page property

_destinations/bigquery/v2/bigquery-setup-v2.md
=> removing a spot where we say Google twice in a row

_saas-integrations/google-analytics/google-analytics-latest.md
This commit was to add to the notes in the "Metrics and Dimensions" section about Stitch not supporting Cohort Reports.
=> Google Analytics - Cohort Report support

_data/taps/extraction/database-setup/user-privileges/mssql.yml, _data/taps/extraction/database-setup/user-privileges/mysql.yml, _data/taps/extraction/database-setup/user-privileges/oracle.yml, _data/taps/extraction/database-setup/user-privileges/postgres.yml, _data/urls.yaml, _includes/integrations/databases/setup/db-users/mssql.html, _includes/integrations/databases/setup/db-users/mysql.html, _includes/integrations/databases/setup/db-users/oracle.html, _includes/integrations/databases/setup/db-users/postgres.html, _troubleshooting/integrations/unable-to-load-tables-too-many-tables.md
This PR:
- Updates the setup instructions for database integrations that require a database user to recommend only granting access to table the user wants to replicate
- Adds a guide about the issues that might be encountered due to a large number of tables being accessed during discovery
=> Database Integrations - Limit database user table access

_includes/integrations/databases/setup/syncing.html, _includes/integrations/databases/verify-mongo-data-types.html, _includes/replication/define-rep-keys.html, _includes/replication/rep-key-gotchas.html, _includes/replication/rep-key-recommendations.html, _includes/replication/rep-key-requirements.html, _includes/replication/rep-keys-vs-primary-keys.html, _includes/replication/reset-rep-keys.html, _replication/replication-keys/mongo-replication-keys.md
This PR clarifies the indexing requirement for fields being used as Replication Keys.
=> MongoDB/v1 - Replication Keys must have a single field index

_data/destinations/bigquery/versions.yml
This PR moves the Google BigQuery v2 destination from `beta` to `released`. It also adds a `date-last-connection` value for v1.
=> Move BQ v2 to released

_data/taps/versions/deputy.yml, _data/taps/versions/helpscout.yml, _data/taps/versions/intacct.yml, _data/taps/versions/liveperson.yml, _data/taps/versions/mambu.yml, _data/taps/versions/ringcentral.yml, _data/taps/versions/sftp.yml
This PR moves several integrations from `beta` to `released`.
=> Multiple integrations/Release to GA

_integration-schemas/asana/v1/tasks.md
This PR adds the `custom_fields` attributes to Asana's `tasks` table. This documents https://github.com/singer-io/tap-asana/pull/7.
=> Asana/v1 - Add custom_fields to tasks table

_data/taps/versions/mailchimp.yml, _integration-schemas/mailchimp/v1/list_members.md
This PR:
- Puts `platform.mailchimp` into `released`
- Adds the `list_id` as a Primary Key attribute for the `list_members` table (https://github.com/singer-io/tap-mailchimp/pull/20)
=> MailChimp/v1 - GA release

_integration-schemas/braintree/transactions.yml
Adds the `subscription ID` attribute to the Transactions table.
=> Braintree - add subscription ID

_saas-integrations/shopify/v1/shopify-v1.md
Added a replication section:
- suggests creating a separate integration for the order refunds table since it's queried at every single ID
=> Shopify - Order Refunds table replication note

_integration-schemas/uservoice/v1/external_users.md
this update changes the link subattributes to make them singular and not plural
=> Uservoice/v1: Update `external_users` table's link sub attributes

_integration-schemas/github/foreign-keys.md, _integration-schemas/github/releases.md
This PR adds the `releases` table and updates the foreign keys.
=> Github/v1 - Add releases table

_integration-schemas/chargebee/20-05-2019/addons.md, _integration-schemas/chargebee/20-05-2019/coupons.md, _integration-schemas/chargebee/20-05-2019/credit_notes.md, _integration-schemas/chargebee/20-05-2019/customers.md, _integration-schemas/chargebee/20-05-2019/events.md, _integration-schemas/chargebee/20-05-2019/foreign-keys.md, _integration-schemas/chargebee/20-05-2019/invoices.md, _integration-schemas/chargebee/20-05-2019/payment_sources.md, _integration-schemas/chargebee/20-05-2019/plans.md, _integration-schemas/chargebee/20-05-2019/subscriptions.md, _integration-schemas/chargebee/20-05-2019/transactions.md, _integration-schemas/chargebee/20-05-2019/virtual_bank_accounts.md, _integration-schemas/chargebee/addons.md, _integration-schemas/chargebee/coupons.md, _integration-schemas/chargebee/customers.md, _integration-schemas/chargebee/events.md, _integration-schemas/chargebee/foreign-keys.md, _integration-schemas/chargebee/gifts.md, _integration-schemas/chargebee/invoices.md, _integration-schemas/chargebee/orders.md, _integration-schemas/chargebee/plans.md, _integration-schemas/chargebee/promotional_credits.md, _integration-schemas/chargebee/subscriptions.md, _integration-schemas/chargebee/transactions.md, _saas-integrations/chargebee/v1/chargebee-v1.md
This pull request updates the following:
-  added the `gifts` and `orders` tables
- updated the `subscriptions`, `addons`, `events`, `customers` and `plans` tables
- mentions in the `orders` table and setup instructions about the order management feature enablement
=> Chargebee schema updates + orders

_data/taps/versions/3plcentral.yml, _data/taps/versions/darksky.yml, _data/taps/versions/dynamodb.yml, _data/taps/versions/linkedin-ads.yml, _data/taps/versions/recharge.yml, _data/taps/versions/saasoptics.yml, _data/taps/versions/shiphero.yml
This PR moves the following integrations from `beta` to `released`:
- 3PL Central
- Darksky
- Amazon DynamoDB
- ReCharge
- SaaSOptics
- Shiphero
=> Move multiple integrations to GA

_integration-schemas/shopify/collects.md, _saas-integrations/mixpanel/mixpanel-latest.md
This update notes not to exceed 365 days for a start date selection.
=> Mixpanel start date limitations

_data/taps/versions/pardot.yml
Updates the release status of platform.pardot and adds deprecation / sunset dates to v 15-10-2015
=> Update pardot version for ga

_data/errors/extraction/databases/mssql.yml, _data/errors/extraction/saas/google-sheets.yml, _data/taps/extraction/replication-methods/key-based-incremental.yml, _data/urls.yaml, _includes/replication/extraction/file-modification-replication-keys.html, _integration-schemas/google-sheets/file_metadata.md, _integration-schemas/google-sheets/foreign-keys.md, _integration-schemas/google-sheets/sample-table.md, _integration-schemas/google-sheets/sheet_metadata.md, _integration-schemas/google-sheets/sheets_loaded.md, _integration-schemas/google-sheets/spreadsheet_metadata.md, _saas-integrations/google-sheets/v1/google-sheets-v1.md, _troubleshooting/errors/extraction-errors/saas/google-sheets-extraction-errors.md
This update includes:
- adding a section to the the replication notes mentioning the "skip worksheet" logic
- adds having a header row as a requirement
=> Google Sheets - Empty worksheets and header row

_integration-schemas/zendesk/users.md
This PR adds the `user_fields` attribute to the `users` table.
=> Zendesk/v1 - Add users_fields to users table

_saas-integrations/appsflyer/appsflyer-latest.md
This PR clarifies the value needed for the `id` field during setup.
=> Appsflyer - update iOS ID info

_data/ui/database-integration-settings/mongo.yml, _includes/integrations/databases/setup/binlog/mongodb-oplog.html
This PR adds info about using `rs.status()` to return replica set names for MongoDB integrations.
=> MongoDB - replica set names

_data/errors/extraction/databases/dynamodb.yml, _data/taps/links/dynamodb.yml, _database-integrations/dynamodb/dynamodb-projection-expressions.md, _includes/shared/integrations/projection-column-selection.html, _troubleshooting/errors/extraction-errors/database-extraction-errors.md
This PR updates the DynamoDB projection expression guide to reflect a recent discovery by support. Encasing double quotes were causing syntax errors, resulting in issues during extraction. The tap seems to encase queries in quotes on its own, so the user entering quotes in Stitch will cause errors.
=> DynamoDB/v1 - Remove quotes from projection expressions

_data/destinations/common/reference-data.yml, _data/errors/extraction/common.yml, _data/import-api/general.yml, _data/import-api/response-codes/batch.yml, _data/import-api/response-codes/general-codes.yml, _data/import-api/response-codes/push.yaml, _data/stitch/notifications/replication.yml, _data/taps/import-api/return-codes.yml, _data/urls.yaml, _getting-started/connecting-other-data-sources-guide.md, _troubleshooting/destinations/aws-io-errors.md, _troubleshooting/destinations/panoply-issues.md, _troubleshooting/destinations/redshift-dependent-view-errors.md, _troubleshooting/destinations/redshift-vacuum-errors.md, _troubleshooting/error-notifications.md, _troubleshooting/errors/connection-errors/database-integration-connection-errors.md, _troubleshooting/errors/connection-errors/destination-connection-errors.md, _troubleshooting/errors/destination-loading-errors.md, _troubleshooting/errors/extraction-errors/database-extraction-errors.md, _troubleshooting/errors/extraction-errors/saas-common-extraction-errors.md, _troubleshooting/errors/extraction-errors/saas/google-sheets-extraction-errors.md, _troubleshooting/errors/extraction-errors/saas/netsuite-suitetalk-extraction-errors.md, _troubleshooting/integrations/reauthorizing-integrations.md, _troubleshooting/integrations/saas-integration-connection-errors.md, _troubleshooting/integrations/salesforce-rest-api-too-many-columns.md, _troubleshooting/integrations/unable-to-load-tables-too-many-tables.md, _webhook-integrations/stitch-incoming-webhooks.md
This PR:
- Updates the max record size limit to 20MB
- Adds the extraction error for records exceeding this size to the docs
- Adds a **Common SaaS extraction errors reference** to the troubleshooting docs
- Single-sources the max record size limit and updates references (data lives in `_data/import-api/general.yml`)
- Re-vamps the **Troubleshooting > Error Notifications** page so it's not a total dump of pages
=> Update max record size limit

_database-integrations/mysql/cloudsql/google-cloudsql-mysql.md, _database-integrations/postgres/cloudsql/v1/google-cloudsql-postgresql-v1.md
This PR adds setup requirements for enabling log-based rep for GCP MySQL-based databases. It also clarifies some requirements for GCP Postgres.
=> GCP MySQL and Postgres - Add setup requirements for log-based rep

_developer-files/connect/api/objects/extractions/list-all-extractions.md
Changes text in the `page` argument of List last extraction jobs for an account to reference extraction jobs rather than load attempts.
=> Extraction_endpoint_correction

Gemfile
This PR adds the `kramdown-parser-gfm` gem to the site's `Gemfile`.
Netlify doesn't seem to be respecting the `Gemfile`, and suddenly started using Jekyll `3.9.0` (and we use `4.1.1`, so ¯\_(ツ)_/¯), which caused problems with this gem. In the 3.9 release of Jekyll, they required that this be added to `Gemfile`s to continue using GitHub-flavored Markdown with Kramdown.
=> Add kramdown-parser-gfm to Gemfile

_data/destinations/bigquery/loading-errors.yml, _data/errors/extraction/databases/mongo.yml, _destinations/redshift/guides/redshift-apply-encodings-sort-dist-keys.md, _includes/integrations/databases/setup/binlog/mongodb-oplog.html, _includes/integrations/databases/setup/db-users/mongo.html, _replication/replication-methods/log-based-incremental-replication.md
This PR addresses the following:
- DOC-1163: Fixes missing Primary Key error message in the Google BQ v2 loading reference
- DOC-1266: Adds info about MongoDD maximum oplog size to the MongoDB, Log-based Incremental Rep, and Database Extraction Errors pages.
- DOC-1317: Corrects SQL client to psql tool in the Amazon Redshift SORT/DIST keys tutorial
=> August 17 support fixes

_saas-integrations/google-sheets/v1/google-sheets-v1.md
Add a note about [the file not found error that occurs when attempting to load a Google Sheet from a shared drive](https://github.com/singer-io/tap-google-sheets/issues/7).
=> Add tip about error to google-sheets-v1.md

_data/taps/versions/impact.yml, _data/taps/versions/kustomer.yml, _data/taps/versions/lever.yml, _data/taps/versions/netsuite-suite-analytics.yml, _data/taps/versions/surveymonkey.yml, _data/taps/versions/ujet.yml, _data/taps/versions/workday-raas.yml
This PR moves the following integrations to `released` status:
- Kustomer
- Impact
- Lever
- Netsuite Suite Analytics
- Ujet
- Survey Monkey
- Workday RaaS
=> Multiple sources: GA release

_integration-schemas/jira/v2/issue_transitions.md
Notes that the `issue_transitions` table is an append only table.
=> Jira append only table

_data/taps/extraction/data-types/postgres/v1.yml
Removes the `format: "date-time" ` line to more accurately represent the tap's functionality
=> PostgreSQL/v1 - Remove date-time formats from data typing

_data/taps/extraction/data-types/postgres/v15-10-2015.yml
Removes the `format: "date-time" from the time type to more accurately represent the previous integration's functionality
=> PostgreSQL/v15-10-2015 - Update time format for data typing

_database-integrations/amazon-s3/amazon-s3-csv-latest.md, _saas-integrations/facebook-ads/facebook-ads-latest.md, _saas-integrations/hubspot/v2/hubspot-v2.md, _saas-integrations/jira/v2/jira-v2.md
This PR updates the docs for the following integrations, which now have table-level reset support:
- Facebook Ads
- JIRA
- Amazon S3 CSV
- HubSpot
=> Table Reset Support for additional SaaS/file integrations

_data/taps/versions/intercom.yml, _data/taps/versions/mixpanel.yml, _data/taps/versions/square.yml
This PR releases v1 of Intercom, Mixpanel, and Square, and deprecates the sourcerer versions.
=> Release v1 of Intercom, Mixpanel, and Square

_data/taps/versions/adroll.yml, _data/taps/versions/trello.yml
This PR releases v1 of Adroll and Trello and deprecates the sourcerer versions.
=> Release Trello and Adroll

_data/destinations/databricks-delta/loading-errors.yml, _data/errors/extraction/saas/pardot.yml, _data/urls.yaml, _destinations/databricks-delta/guides/databricks-delta-destination-setup.md, _integration-schemas/marketo/activities.md, _integration-schemas/marketo/activity_types.md, _integration-schemas/marketo/campaigns.md, _integration-schemas/marketo/leads.md, _integration-schemas/marketo/lists.md, _integration-schemas/marketo/programs.md, _integration-schemas/square/v1/customers.md, _saas-integrations/marketo/marketo-latest.md, _saas-integrations/pardot/v1/pardot-v1.md, _troubleshooting/errors/destination-loading-errors.md, _troubleshooting/errors/extraction-errors/saas/pardot-extraction-errors.md
This PR:
- Adds a note about specific AWS region requirements for S3 bucket setup for Databricks Delta Lake destinations
- Adds a requirement to the Pardot docs to use a user with a UTC preferred timezone to auth the integration
- Removes Marketo Corona from the docs and clarifies how replicating the `leads` table works
- Adds the `customers` table to the Square integration docs
=> Support Issues: 10/26/2020

_integration-schemas/shopify/customers.md
Adds `accepts_marketing_updated_at` field to the customer table.
Context: This is the Sources' PR for this update: https://github.com/singer-io/tap-shopify/pull/69/files
It says that they added this as an `anyOf` field, but the Shopify docs says that this is a date-time field. I put in in the docs as a date-time field too.
=> Shopify - Add attribute to customers table

_integration-schemas/pendo/v1/visitor_history.md
This PR uncomments the `visitor_history` table and updates its Replication Key as per https://github.com/singer-io/tap-pendo/pull/17.
=> Pendo - update rep key

_integration-schemas/pendo/v1/guide_events.md, _integration-schemas/pendo/v1/guides.md, _integration-schemas/pendo/v1/poll_events.md
change `guides` and `poll_events` tables' replication keys to `browserTime` (source: https://github.com/singer-io/tap-pendo/pull/21)
=> Pendo - update rep keys

_integration-schemas/square/v1/payments.md
This PR updates the link to the `payments` endpoint for the Square `payments` table.
=> Square - update `payments` api link

_changelog/entries/2021/2021-03-09-adwords-v05-02-2017-common-error-messages.md, _changelog/entries/2021/2021-03-10-pendo-v1-accounts-visitors-custom-fields.md, _changelog/entries/2021/2021-03-11-salesforce-v1-error-message-formatting.md, _changelog/entries/2021/2021-03-11-zuora-v1-aqua-jobs-rate-limit.md, _changelog/entries/2021/2021-03-12-mongodb-v2-remove-duplicate-instances.md, _changelog/entries/2021/2021-03-12-pendo-v1-ijson-performance-enhancement.md, _changelog/entries/2021/2021-03-15-zoom-v1-fixed-schema-report-meetings-webinars.md
This PR adds changelog entries for these pull requests:
- https://github.com/singer-io/tap-adwords/pull/77
- https://github.com/singer-io/tap-mongodb/pull/58
- https://github.com/singer-io/tap-pendo/pull/27
- https://github.com/singer-io/tap-pendo/pull/28
- https://github.com/singer-io/tap-salesforce/pull/96
- https://github.com/singer-io/tap-zoom/pull/4
- https://github.com/singer-io/tap-zuora/pull/53
=> Change Log Entries - starting from 2021-03-09

_data/connect/api.yml, _data/connect/code-examples/streams.yml, _data/stitch/notifications/replication.yml, _data/taps/extraction/data-types/postgres/v1.yml, _developer-content/connect/guides/api/select-tables-and-fields.md, _developer-files/connect/api/objects/destinations/v3/create-a-destination-v3.md, _developer-files/connect/api/objects/destinations/v3/destination-object-v3.md, _developer-files/connect/api/objects/destinations/v3/update-a-destination-v3.md, _developer-files/connect/api/objects/destinations/v4/create-a-destination-v4.md, _developer-files/connect/api/objects/destinations/v4/destination-object-v4.md, _developer-files/connect/api/objects/destinations/v4/update-a-destination-v4.md, _developer-files/connect/api/objects/notifications/custom-emails/create-custom-email-recipient.md, _developer-files/connect/api/objects/notifications/post-load-hooks/create-hook-notification.md, _developer-files/connect/api/objects/sources/create-a-source.md, _developer-files/connect/api/objects/sources/sources-object.md, _developer-files/connect/api/objects/sources/update-a-source.md, _includes/integrations/shared-setup/aws-s3-iam-setup.html, _includes/integrations/shared-setup/configure-table-settings-file-server.html, _integration-schemas/braintree/transactions.yml, _integration-schemas/jira/v2/changelogs.md, _integration-schemas/linkedin-ads/v1/ad_analytics_by_campaign.md, _integration-schemas/linkedin-ads/v1/ad_analytics_by_creative.md, _integration-schemas/netsuite-suite-analytics/v1/budget.md, _replication/selecting-data/syncing-new-additional-columns.md, _saas-integrations/linkedin-ads/v1/linkedin-ads-v1.md, _saas-integrations/yotpo/yotpo-v1.md, _webhook-integrations/branch.md
This PR:
- Corrects cURL examples using the incorrect HTTP methods
- Clarifies behavior of the **Directory** field for file system-based database integrations
- Adds info about API limitations for `changelogs` in the JIRA integration
- Adds info about attribution windows for LinkedIn Ads integrations
- Fixes broken anchor links for connection property objects in the API docs
- Adds the `paypal_details` object to Braintree's `transactions` schema documentation
- Updates the setup instructions for Branch integrations based on their UI updates
- Fixes a few typos
=> Support updates: 5/11/2021

_changelog/entries/2021/2021-05-17-mssql-v1-bugfix-rep-key-quoting.md, _changelog/entries/2021/2021-05-19-shopify-v1-abandoned-checkouts-validation.md, _changelog/entries/2021/2021-05-24-slack-v1-user-profile-data.md, _integration-schemas/shopify/abandoned_checkouts.md, _integration-schemas/shopify/orders.md, _integration-schemas/shopify/products.md, _integration-schemas/slack/v1/users.md, _saas-integrations/slack/v1/slack-v1.md
This PR adds entries for the following:
- https://github.com/singer-io/tap-slack/pull/16
- https://github.com/singer-io/tap-shopify/pull/44
- https://github.com/singer-io/tap-mssql/pull/59
=> Changelog - May 17 - 24

_data/taps/extraction/file-systems/file-requirements.yml
This PR adds `.gz` compression and `.jsonl` file type support for the Amazon S3 CSV integration.
Documents these PRs:
- https://github.com/singer-io/tap-s3-csv/pull/31
- https://github.com/singer-io/tap-s3-csv/pull/32
=> Amazon S3 CSV/v1 - Add .gz compression + .jsonl file support

_changelog/entries/2021/2021-06-24-shopify-v1-plus-permissions.md, _integration-schemas/shopify/customers.md, _saas-integrations/shopify/v1/shopify-v1.md
This PR adds info about possible permission requirements for Shopify Plus plan users to the Shopify docs.
=> Shopify - Shopify Plus permissions

_saas-integrations/campaign-manager/campaign-manager-v1.md
The API has a new name, but the link is still the same.
=> Campaign Manager (v1) - Update API from 3.2 to 3.5

scripts/tap-generate-docs/src/tap_generate_docs.clj
Log the bad field in the file we are currently processing
The old logs
```
vagrant@vagrant:/opt/code/docs$ ./bin/tap-generate-docs facebook
WARNING: Use of -A with clojure.main is deprecated, use -M instead
Processing file: /opt/code/tap-facebook/tap_facebook/schemas/campaigns.json
Writing converted /opt/code/tap-facebook/tap_facebook/schemas/campaigns.json to campaigns.md
Processing file: /opt/code/tap-facebook/tap_facebook/schemas/ads_insights.json
Execution error (ExceptionInfo) at tap-generate-docs/parse-json-schema-reference (tap_generate_docs.clj:176).
Malformed json-schema-reference
Full report at:
/tmp/clojure-15093173328980073991.edn
```
The new logs
```
vagrant@vagrant:/opt/code/docs$ ./bin/tap-generate-docs facebook
WARNING: Use of -A with clojure.main is deprecated, use -M …
```
=> Add debug logging

_integration-schemas/outreach/v1/events.md
This PR adds the `name` field to the `events` table (https://github.com/singer-io/tap-outreach/pull/10)
=> Outreach/v1 - Add `name` to `events` table

_changelog-files/2021/2021-05-21-typeform-v1-forms-table.md, _integration-schemas/typeform/foreign-keys.md, _integration-schemas/typeform/forms.md, _integration-schemas/typeform/questions.md, _saas-integrations/typeform/v1/typeform-v1.md
This PR updates the Typeform (v1) docs to include the new `forms` table. (https://github.com/singer-io/tap-typeform/pull/29)
=> Typeform/v1 - Add forms table

_data/connect/common/database-sources.yml, _database-integrations/mysql/vanilla/mysql-v2.md, _developer-files/connect/api/objects/form-properties/sources/databases/amazon-aurora-object.md, _developer-files/connect/api/objects/form-properties/sources/databases/google-cloudsql-mysql.md, _developer-files/connect/api/objects/form-properties/sources/databases/hp-mysql-object.md, _developer-files/connect/api/objects/form-properties/sources/databases/mariadb-object.md, _developer-files/connect/api/objects/form-properties/sources/databases/mysql-object.md
The `filter_dbs` field is now user-provided in hpt-mysql, so I removed this field from the common mysql fields, added it to all other mysql sources with the previous values and added it with the new values for hp-mysql.
=> TDL-16557 updated doc for filter_dbs

_getting-started/free-trial.md, _includes/layout/topnav.html
This PR includes:
- Updates the Stitch docs top navigation 'Sign Up' link to take you directly to the web app sign up page
- Create a 'Free Trial' page so that it comes up in the Intercom search results
There may be several launches/versions of this so that Marketing can test an analyze the effectiveness of the changes.
=> Free Trial Page & Top Nav update (v1)

_data/destinations/bigquery/v2/stitch-details.yml
Last week I made a change, enabled by some recent infrastructure work, to enable the static IP addresses for BigQuery V2. That has been confirmed to be working, so this PR is to propagate that change to the documentation!
=> Bigquery V2 now uses our static IP addresses

scripts/tap-generate-docs/bin/test
This PR fixes the following error
```shell
#!/bin/bash -eo pipefail cd scripts/tap-generate-docs/ bin/test
-C is no longer supported, use -A with repl, -M for main, -X for exec, -T for tool
```
I originally thought this was broken because the Docker image we use was updated recently. But just judging by the version numbers, I would've expected this to break a long time ago
- [Docker File History](https://github.com/Quantisan/docker-clojure/commits/6a44a1a9f0343fcd60cae124b92ff0041e479f96/target/eclipse-temurin-17-jdk-jammy/tools-deps/Dockerfile)
Not really worth digging into.
- Ran the failing command and the new command
- Low. It can't get more broken than it already is
=> Update test script to work with `Clojure CLI version 1.11.1.1252`

_includes/layout/sidebars/on-page-sidebar.html
The HTML structure in the sidebar was missing a `</li>` in the lower levels of the list.
Search for `#system-architecture--preparing--menu` in the HTML source of for instance the [Basic Concepts and System Overview](https://www.stitchdata.com/docs/getting-started/basic-concepts-system-overview) page – the parent `<li>` is not closed.
- Someone else has already found the problem and fixed it
=> fix: Added missing `</li>` in the sidebar

_data/destinations/microsoft-sql-server/user-privileges.yml, _data/destinations/mysql/user-privileges.yml, _destinations/microsoft-sql-server/guides/connecting-amazon-rds-for-sql-server.md, _destinations/microsoft-sql-server/guides/connecting-azure-sql-database.md, _destinations/microsoft-sql-server/guides/connecting-azure-sql-managed-instance.md, _destinations/mysql/guides/connecting-amazon-aurora-mysql.md, _destinations/mysql/guides/connecting-amazon-rds-for-mysql.md, _destinations/mysql/guides/connecting-mariadb-mysql.md
=> TDL-24621 + TDL-24622 Add guides for different MSSQL and MySQL environments

_includes/notifications/status-support/support.html
Feedback from HubSpot regarding out setup instructions for HubSpot:
>Please update the [setup guide](https://www.stitchdata.com/docs/integrations/saas/hubspot) to further distinguish your brand. For example, the portion “ HubSpot is supported by Stitch” may imply to customers that Stitch supports HubSpot. I recommend this to be updated to “ Stitch integration with HubSpot is supported by Stitch” or “Connection with HubSpot in Stitch is supported by Stitch.”
I have updated the text to indicate what we are supporting is the integration, not HubSpot themselves.
- 
- 
=> update wording to enable hubspot certification

_data/ui/common/database-connections.yml, _data/ui/database-integration-settings/mysql.yml
https://jira.talendforge.org/browse/TDL-17973 
- 
- 
=> TDL-17972 Removed dbname

scripts/json/get_json_files.py
=> cleaned up unused functions

_data/taps/extraction/file-systems/file-requirements.yml, _database-integrations/sftp/v1/sftp-v1.md
=> TDL-24642 document encoding format option

scripts/changelog/changelog.py
https://qlik-dev.atlassian.net/browse/DAGE-465
- 
- 
=> DAGE-465: Fixed missing curly brackets and added new words
