- _saas-integrations/salesforce/salesforce-latest.md
This PR fixes a minor issue in the display of Salesforce’s setup instructions.
> Salesforce: Fix setup display

- _account-security/stitch-security.md
> Post-HIPAA updates

- _saas-integrations/zuora.md
This PR adds language to the setup steps for Zuora for connecting a sandbox account.
> Add Zuora Sandbox setup step

- _destinations/redshift.md
- _destinations/redshift/connecting-redshift.md
- _includes/destinations/setup/destination-settings.html
This PR adds info about default usage of SSL for Redshift destination connections.
> Redshift: Default SSL connections

- _data/errors/connection-checks.yml
- _data/urls.yaml
- _troubleshooting/destinations/aws-io-errors.md
This PR adds a troubleshooting doc for destination I/O errors.
> Destination I/O errors

- _includes/connect/overview-toolkit-tiles.html
This PR fixes a small link issue in the Connect docs.
> Connect link fix

- _account-security/billing-faq.md
- _account-security/managing-team-members.md
- _data/stitch/subscription-plans.yml
This PR updates the docs to reflect recent pricing changes.
> Pricing updates

- _account-security/managing-account-settings.md
- _account-security/stitch-security.md
- _config.yml
- _destinations/amazon-s3.md
- _destinations/destinations.md
- _includes/enterprise-cta.html
- _replication/integration-extraction-logs.md
- _replication/integration-loading-reports.md
This PR adds notice/alert boxes to features that are part of Enterprise plans.
> Add Enterprise notices

- _destinations/data-dot-world.md
This PR sets the data.world `fully-managed` property to `true`, as it's a fully managed destination.
> set data.world fully-managed prop to true

- _destinations/amazon-s3.md
This PR changes the status of Amazon S3 (destination) to `Open Beta`.
> Amazon S3: Open beta

- .gitignore
- _includes/integrations/templates/schemas/table-schemas.html
- _includes/integrations/templates/schemas/table-snapshot.html
- _integration-schemas/github/assignees.md
- _integration-schemas/github/collaborators.md
- _integration-schemas/github/commits.md
- _integration-schemas/github/foreign-keys.md
- _integration-schemas/github/issues.md
- _integration-schemas/github/pull_requests.md
- _integration-schemas/github/reviews.md
- _integration-schemas/github/stargazers.md
- _saas-integrations/github/github-latest.md
- scripts/schema_to_yaml.rb
This PR adds documentation for the [community-supported GitHub integration](https://github.com/singer-io/tap-github).
> GitHub: v1

- _includes/integrations/templates/saas-integration-snapshot.html
- _includes/integrations/webhooks/define-primary-key.html
- _includes/integrations/webhooks/webhook-replication.html
- _includes/integrations/webhooks/webhook-setup.html
- _webhook-integrations/mandrill.md
Change Mandrill to be incoming webhooks
> Mandrill: Update status

- _data/taps/versions/marketo.yml
- _integration-schemas/marketo/activities.md
- _integration-schemas/marketo/activity_types.md
- _integration-schemas/marketo/campaigns.md
- _integration-schemas/marketo/leads.md
- _integration-schemas/marketo/lists.md
- _integration-schemas/marketo/programs.md
- _integration-schemas/marketo/v1/activities.md
- _integration-schemas/marketo/v1/activity_types.md
- _integration-schemas/marketo/v1/leads.md
- _integration-schemas/marketo/v1/lists.md
- _saas-integrations/marketo/marketo-latest.md
- _saas-integrations/marketo/v1/marketo-v1.md
This PR adds documentation for the impending rollout of v2 of the Marketo integration.
> Marketo: v2.0

- _includes/integrations/saas/ads-append-only-replication.html
This PR fixes a typo in a link in an include file.
> update link to column selection

- _data/stitch/sdc-columns.yml
> Fix a typo in _sdc column copy

- _replication/syncing-data.md
> Typo update (Sufficient)

- _data/errors/database-extraction/mysql.yml
- _data/taps/extraction/database-queries.yml
- _data/urls.yaml
- _database-integrations/amazon-aurora.md
- _database-integrations/google-cloudsql-mysql.md
- _database-integrations/google-cloudsql-postgresql.md
- _database-integrations/heroku.md
- _database-integrations/magento.md
- _database-integrations/mariadb.md
- _database-integrations/microsoft-sql-server-amazon-rds.md
- _database-integrations/microsoft-sql-server.md
- _database-integrations/mongodb.md
- _database-integrations/msazure.md
- _database-integrations/mysql-amazon-rds.md
- _database-integrations/mysql.md
- _database-integrations/postgres-amazon-rds.md
- _database-integrations/postgres.md
- _includes/layout/troubleshooting-articles.html
- _includes/replication/databases/extraction-queries.html
- _includes/troubleshooting/error-messages.html
- _troubleshooting/errors/database-integration-connection-errors.md
- _troubleshooting/errors/destination-connection-errors.md
- _troubleshooting/errors/mysql-extraction-errors.md
This PR adds troubleshooting documentation for MySQL extraction errors.
> MySQL extraction errors

- _destinations/amazon-s3.md
Changes release status of S3 destination.
> Amazon S3 destination: Update release status

- _account-security/billing-faq.md
- _database-integrations/mongo/mongodb.md
- _drafts/hubspot-DEPRECATED.md
- _includes/integrations/templates/connection-instructions.html
- _includes/integrations/templates/database-connection-instructions.html
- _saas-integrations/closeio.md
- _saas-integrations/desk.md
- _saas-integrations/hubspot/v01-03-2017/hubspot-v01-03-2017.md
- _saas-integrations/hubspot/v1/hubspot-v1.md
- _saas-integrations/hubspot/v2/hubspot-v2.md
- _saas-integrations/intercom/intercom-latest.md
- _saas-integrations/jira.md
- _saas-integrations/marketo/marketo-latest.md
- _saas-integrations/marketo/v1/marketo-v1.md
- _saas-integrations/netsuite.md
- _saas-integrations/pardot.md
- _saas-integrations/quickbooks.md
- _saas-integrations/recurly.md
- _saas-integrations/salesforce/salesforce-latest.md
- _saas-integrations/salesforce/v15-10-2015/salesforce-v15-10-2015.md
- _saas-integrations/zendesk-chat.md
- _saas-integrations/zendesk/v-15-10-2015/zendesk-v15-10-2015.md
- _saas-integrations/zendesk/zendesk-latest.md
- _saas-integrations/zuora/v15-10-2015/zuora-15-10-2015.md
- _saas-integrations/zuora/zuora-latest.md
- _templates/integrations/saas.md
- _templates/integrations/webhook.md
This PR changes the term `Premium`, which describes integrations that require a paid Stitch subscription, to `Paid`.
> Make "Premium" > "Paid"

- _connect-files/api/objects/form-properties/sources/amazon-aurora-object.md
- _connect-files/api/objects/form-properties/sources/google-cloudsql-mysql.md
- _connect-files/api/objects/form-properties/sources/mariadb-object.md
- _connect-files/api/objects/form-properties/sources/mysql-object.md
- _connect-files/api/objects/form-properties/sources/postgresql-object.md
- _data/connect/api.yml
- _data/sidebars/connect.yml
This PR adds PostgreSQL to the Connect docs, as it got skipped during the initial Postgres launch.
> Postgres/v1 - Add to Connect

- _troubleshooting/data-discrepancies/non-replicating-data-unsupported-data-types.md
This PR fixes the supported data type tab in the corresponding troubleshooting doc.
> Fix data type troubleshooting doc

- _account-security/stitch-security.md
Add security Q&A item for SOC 2 compliance
> Add SOC q&a

- _saas-integrations/zendesk/zendesk-latest.md
changes `singer: false` to `singer: true`
> Zendesk/v1 - Add repo-url & update Singer flag

- _data-structure/integration-schemas.md
- _data/app.yml
- _data/dataloading/deleted-records.yml
- _data/sidebars/stitchnav.yml
- _data/stitch/sdc-columns.yml
- _data/taps/extraction/replication-methods.yml
- _data/urls.yaml
- _includes/replication/deleted-record-examples.html
- _includes/replication/replication-methods-deleted-records.html
- _includes/stitch/stitch-system-table.html
- _replication/deleted-record-handling.md
- _replication/replication-methods.md
This PR improves the documentation for deleted record handling, and adds new docs for `_sdc_deleted_at`.
> Deleted records

- _data/sidebars/stitchnav.yml
- _data/stitch/sdc-columns.yml
This PR adds some `_sdc` columns to the documentation and creates additional sidenav links.
> Add _sdc to sidenav and list

- _account-security/stitch-security.md
This is an important topic that should be addressed in our docs.
> add GDPR language to security page

- _database-integrations/amazon-s3/amazon-s3-csv-latest.md
- _database-integrations/mongo/mongodb.md
- _database-integrations/mssql/amazon-rds/microsoft-sql-server-amazon-rds.md
- _database-integrations/mssql/azure/msazure.md
- _database-integrations/mssql/microsoft-sql-server.md
- _database-integrations/mysql/aurora-rds/amazon-aurora.md
- _database-integrations/mysql/cloudsql/google-cloudsql-mysql.md
- _database-integrations/mysql/magento/magento-latest.md
- _database-integrations/mysql/mariadb/mariadb-latest.md
- _database-integrations/mysql/mysql-latest.md
- _replication/syncing-database-views.md
This PR fixes the display of the list of databases that support view replication.
> Fix database view support list

- _connect-files/api/objects/form-properties/sources/saas/harvest-forecast-object.md
- _integration-schemas/harvest-forecast/assignments.md
- _integration-schemas/harvest-forecast/clients.md
- _integration-schemas/harvest-forecast/foreign-keys.md
- _integration-schemas/harvest-forecast/milestones.md
- _integration-schemas/harvest-forecast/people.md
- _integration-schemas/harvest-forecast/projects.md
- _saas-integrations/harvest-forecast/harvest-forecast-latest.md
This PR adds documentation for the new Harvest Forecast integration.
> Harvest Forecast/v1

- _data/taps/extraction/database-setup/server-settings/mysql.yml
- _database-integrations/mysql/aurora-rds/amazon-aurora.md
- _database-integrations/mysql/mysql-latest.md
- _includes/integrations/databases/setup/binlog/amazon-rds/aurora-rds.html
- _includes/integrations/databases/setup/binlog/vanilla-mysql.html
This PR updates the instructions for setting up vanilla MySQL and Aurora MySQL RDS.
> MySQL updates

- _data/ui/database-integration-settings/mysql.yml
Added resources to point users towards min / max server id values that can be supported by mysql
> MySQL: Add min/max server ID resource

- _integration-schemas/zendesk/organizations.md
- _integration-schemas/zendesk/ticket_forms.md
- _integration-schemas/zendesk/users.md
- _saas-integrations/zendesk/zendesk-latest.md
This PR:
- Adds info about the requirements for replicating `ticket_forms`
- Adds info about the requirements for replicating user and organization custom fields
> Zendesk: Add requirements to ticket_forms, users, and organizations

- _database-integrations/mssql/microsoft-sql-server.md
Adds minimum supported version based on JDBC driver's supported minimum version.
> MSSQL: Add supported versions

- _saas-integrations/marketo/marketo-latest.md
Here's what they say: http://developers.marketo.com/rest-api/
```
Daily Quota: Most subscriptions are allocated 50,000 API calls per day (which resets daily at 12:00AM CST).  You can increase your daily quota through your account manager.
```
> Add a note about the max-daily-api calls

- _data/taps/import-api/return-codes.yml
This PR adds documentation for the Import API’s 202 response.
> Import API - 202 response

- _data/errors/connection-checks.yml
- _destinations/amazon-s3/setup/connecting-amazon-s3.md
- _troubleshooting/errors/database-integration-connection-errors.md
- _troubleshooting/errors/destination-connection-errors.md
This PR adds documentation about the error that will result in a missing challenge file in an S3 bucket. It also adds the steps necessary to resolve the error.
> S3 destination - Challenge file error

- _troubleshooting/integrations/stale-salesforce-data-formula-fields.md
This PR updates the workarounds for Salesforce formula field issues to include using Full Table Replication.
> update formula fields workarounds

- _data-structure/integration-schemas.md
- _data-structure/rejected-records.md
- _data/destinations/reference/microsoft-azure.yml
- _data/stitch/sdc-primary-keys.yml
- _destinations/microsoft-azure/primary-key-handling.md
- _destinations/microsoft-azure/setup/connecting-microsoft-azure-ssh-tunnel.md
- _destinations/microsoft-azure/setup/connecting-microsoft-azure.md
This PR makes some minor corrections to the docs for the Azure SQL DW destination.
> Azure SQL DW: QA review

- _saas-integrations/marketo/marketo-latest.md
This PR updates the Marketo docs to include table selection steps.
> add table selection steps to marketo documentation

- _data/sidebars/stitchnav.yml
- _data/urls.yaml
- _destinations/microsoft-azure/setup/connecting-microsoft-azure.md
This PR fixes some copypasta that made its way into the Azure SQL DW destination docs.
> fix links for azure

- _data/destinations/loading/user-privileges/redshift.yml
This PR adds a title for the ownership permission required to connect a Redshift destination.
> Redshift: Add ownership permission title

- _saas-integrations/quickbooks/quickbooks-latest.md
I didn't see this explicitly mentioned. And in response to a customer's confusion, I am submitting this quick suggested change.
> Added note about Quickbooks for Desktop

- _replication/integration-loading-reports.md
> Update integration-loading-reports.md fix typo

- _saas-integrations/square/square-latest.md
This PR makes the Square integration certified and adds the `square_` prefix back to the table names.
> update square to make it certified and add square_

- _data/stitch/supported-data-types.yml
Til we can determine if / where it is supported
> Remove VARBINARY for now

- _data/destinations/reference/amazon-s3.yml
- _data/destinations/reference/bigquery.yml
- _data/destinations/reference/defaults.yml
- _data/destinations/reference/microsoft-azure.yml
- _data/destinations/reference/panoply.yml
- _data/destinations/reference/postgres.yml
- _data/destinations/reference/redshift.yml
- _data/destinations/reference/snowflake.yml
- _destinations/choosing-a-stitch-destination.md
- _includes/destinations/destination-rollup.html
This PR fixes some display issues in the Choosing a Destination guide that were introduced as a result of #207 .
> Fixes to the Choosing a Destination Guide

- _connect-files/api/objects/form-properties/sources/databases/mysql-object.md
- _data/ui/database-integration-settings/mysql.yml
- _database-integrations/mongo/mongodb.md
- _database-integrations/mssql/amazon-rds/microsoft-sql-server-amazon-rds.md
- _database-integrations/mssql/azure/msazure.md
- _database-integrations/mssql/microsoft-sql-server.md
- _database-integrations/mysql/amazon-rds/mysql-amazon-rds.md
- _database-integrations/mysql/aurora-rds/amazon-aurora.md
- _database-integrations/mysql/cloudsql/google-cloudsql-mysql.md
- _database-integrations/mysql/mariadb/mariadb-latest.md
- _database-integrations/mysql/mysql-latest.md
- _database-integrations/postgres/amazon-rds/v1/postgresql-amazon-rds-v1.md
- _database-integrations/postgres/amazon-rds/v15-10-2015/postgres-amazon-rds-v15-10-2015.md
- _database-integrations/postgres/cloudsql/v1/google-cloudsql-postgresql-v1.md
- _database-integrations/postgres/cloudsql/v15-10-2015/google-cloudsql-postgresql-v15-10-2015.md
- _database-integrations/postgres/heroku/v1/heroku-v1.md
- _database-integrations/postgres/heroku/v15-10-2015/heroku-v15-10-2015.md
- _database-integrations/postgres/vanilla/v1/postgres-v1.md
- _database-integrations/postgres/vanilla/v15-10-2015/postgres-v15-10-2015.md
- _includes/integrations/databases/setup/database-integration-settings.html
This PR adds documentation for the recent MySQL SSL enhancements. Stitch now supports custom certificates and client authentication.
> MySQL SSL enhancements

- _database-integrations/mssql/microsoft-sql-server.md
This page indicated that we supported log-based replication for ms sql server, though we do not currently.
> MS SQL replication method changes

- _saas-integrations/salesforce/salesforce-latest.md
clarifies configurable replication methods
> Salesforce: Remove duplicate Frontmatter parameter

- _saas-integrations/jira/v1/jira-v1.md
Changes the location of the user menu (bottom left, not bottom right)
> Jira/v1 - Setup instructions

- scripts/tap-generate-docs/deps.edn
- scripts/tap-generate-docs/src/tap_generate_docs.clj
- scripts/tap-generate-docs/test/tap_generate_docs_test.clj
* Add checks to parse-json-schema-reference
* Add tests to prove changes
> Improve the tap-generate-docs script

- _database-integrations/mysql/magento/magento-latest.md
- _includes/integrations/databases/setup/db-users/mysql.html
This PR fixes the display of the setup instructions for Magento.
> Magento/v1 - Fix setup instructions

- _data/sidebars/stitchnav.yml
somehow this tiny thing caught my eye!
> fix editor typo

- _data/taps/extraction/netsuite/netsuite-permissions.yml
- _saas-integrations/netsuite/v1/netsuite-v1.md
Removes `Access Token Management` which is necessary for configuring the Stitch integration, but not for data extraction.
> Update NetSuite Permissions

- _data/taps/versions/netsuite.yml
- _saas-integrations/netsuite/v1/netsuite-v1.md
- _saas-integrations/netsuite/v10-15-2015/netsuite-v10-15-2015.md
This PR releases NetSuite v1 🎉
> Netsuite/v1 GA release

- _saas-integrations/wootric/wootric-latest.md
User wrote in asking about Wootric timeline.
> Wootric is not coming soon

- _includes/layout/feedback.html
- _includes/layout/footer-cta.html
- _includes/layout/footer.html
- _includes/layout/related-articles.html
- _includes/layout/related-troubleshooting-articles.html
- _includes/layout/sidebars/connect-sidebar.html
- _includes/layout/sidebars/general-sidebar.html
- _includes/layout/sidebars/on-page-sidebar.html
- _includes/layout/sidebars/tutorial-sidebar.html
- _includes/layout/toc.html
- _includes/layout/topnav.html
- _layouts/default.html
- index.md
- sass/_layout.scss
- stylesheets/screen.css
This PR adds Swiftype search to the docs 🎉
> Install Swiftype

- _includes/integrations/saas/netsuite-permission-list.html
Not entirely sure about my phrasing.
> Update NetSuite Permissions re: features

- _connect-files/api/objects/details/details-object.md
- _connect-files/api/objects/report-cards/sources/source-report-card-object.md
- _connect-files/api/objects/source-types/get-a-source-type.md
- _connect-files/api/objects/source-types/list-source-types.md
@erinkcochran87 I had trouble running/installing jekyll locally. I'm still trying to make sure this all works, but I wanted to pass this along for your review ASAP.
> add default_start_date to all sources

- _integration-schemas/jira/issues.md
Changes the order between steps 3 and 4 to clarify the race condition
> Fix order of deletion workflow for Jira issues

- _connect-files/api/documentation/api-introduction.md
- _connect-files/api/objects/replication-jobs/start-a-replication-job-v4.md
- _connect-files/api/objects/sources/pause-a-source.md
- _connect-files/api/objects/sources/sources-object.md
- _connect-files/api/objects/sources/unpause-a-source.md
- _connect-files/api/objects/sources/update-a-source.md
- _data/connect/api.yml
- _data/sidebars/connect.yml
This PR updates the API docs to include endpoints for pausing and unpausing a data source.
> Connect: Add pause/unpause source endpoints

- _data/taps/extraction/database-setup/user-privileges/mongo.yml
- _includes/integrations/databases/setup/db-users/mongo.html
Used existing code for the 2.x code sample, and mongo's sample code for the 3.x "createUser".
Additionally used mongo's examples for the connection string
**Mongo 3.x Docs:** https://docs.mongodb.com/manual/reference/method/db.createUser/
**Mongo 2.x Docs:** http://www.dba86.com/docs/mongo/2.4/reference/method/db.addUser.html
**Connection String Docs:** https://docs.mongodb.com/manual/mongo/
> Added mongo code samples & file

- _account-security/billing/billing-faq.md
- _account-security/enterprise-features.md
- _account-security/settings/manage-stitch-api-keys.md
- _account-security/settings/managing-team-members.md
- _data/sidebars/stitchnav.yml
- _data/stitch/subscription-plans.yml
- _data/stitch/subscription-plans/all-plans.yml
- _data/stitch/subscription-plans/basic.yml
- _data/stitch/subscription-plans/enterprise.yml
- _data/stitch/subscription-plans/free.yml
- _data/stitch/subscription-plans/premier.yml
- _data/stitch/subscription-plans/standard.yml
- _data/stitch/subscription-plans/starter.yml
- _data/urls.yaml
- _database-integrations/oracle/oracle-v1.md
- _replication/extraction-tab/integration-extraction-logs.md
- _replication/replication-progress/integration-loading-reports.md
This PR adds a dedicated page for Enterprise features to the docs, and makes some updates to how subscription-plan data files are used.
> Add Enterprise page

- _integration-schemas/stripe/v1/foreign-keys.md
- _integration-schemas/stripe/v1/invoice_items.md
- _integration-schemas/stripe/v1/invoice_line_items.md
- _integration-schemas/stripe/v1/plans.md
- _integration-schemas/stripe/v1/products.md
- _integration-schemas/stripe/v1/subscription_items.md
- _integration-schemas/stripe/v1/subscriptions.md
This PR adds docs for the `products` stream for the Stripe integration.
> Add products stream to Stripe

- _data/taps/versions/mssql.yml
- _database-integrations/mssql/amazon-rds/v06-01-2016/microsoft-sql-server-amazon-rds-v06-01-2016.md
- _database-integrations/mssql/amazon-rds/v1/microsoft-sql-server-amazon-rds-v1.md
- _database-integrations/mssql/azure/v06-01-2016/microsoft-azure-v06-01-2016.md
- _database-integrations/mssql/azure/v1/microsoft-azure-v1.md
- _database-integrations/mssql/vanilla/v06-01-2016/microsoft-sql-server-v06-01-2016.md
- _database-integrations/mssql/vanilla/v1/microsoft-sql-server-v1.md
This PR releases Microsoft SQL Server v/1 to GA.
> Release MSSQL/v1 to GA

- _data-structure/reserved-keywords.md
- _data/destinations/reference/bigquery.yml
- _data/destinations/reference/defaults.yml
- _data/destinations/reference/microsoft-azure.yml
- _data/destinations/reference/panoply.yml
- _data/destinations/reference/postgres.yml
- _data/destinations/reference/redshift.yml
- _data/destinations/reference/snowflake.yml
- _data/destinations/resource-links.yml
- _data/sidebars/stitchnav.yml
- _data/stitch/reserved-keywords.yml
- _data/urls.yaml
This PR adds documentation for Stitch and destination-reserved keywords.
> Add reserved keywords documentation

- _database-integrations/mssql/amazon-rds/v1/microsoft-sql-server-amazon-rds-v1.md
- _database-integrations/mssql/vanilla/v1/microsoft-sql-server-v1.md
Pending confirmation from sources.
> Update Versions for platform.mssql

- _data/taps/extraction/salesforce/blacklisted-objects.yml
added new objects based on https://github.com/singer-io/tap-salesforce/blob/master/tap_salesforce/salesforce/__init__.py
> Update SF blacklisted objects

- _developers/post-load-webhooks-reference.md
Talend pipeline designer job integration is planned for the future
> updated wording to correctly reference talend Cloud

- _account-security/account-security.md
- _account-security/settings/manage-stitch-api-keys.md
- _account-security/settings/managing-account-settings.md
- _account-security/settings/managing-stitch-partner-account-access.md
- _account-security/settings/notifications/manage-notification-settings.md
- _account-security/settings/notifications/notifications-guide.md
- _data/app.yml
- _data/sidebars/stitchnav.yml
- _data/stitch/notifications/account.yml
- _data/stitch/notifications/destination.yml
- _data/stitch/notifications/integration.yml
- _data/stitch/notifications/replication.yml
- _data/urls.yaml
This PR updates the docs for the new opt-out of replication error email notifications feature.
> Opt-out replication error notifications

- _data/taps/versions/mongo.yml
- _database-integrations/mongo/mongo-atlas/v1/mongodb-atlas-v1.md
- _database-integrations/mongo/vanilla/v1/mongodb-v1.md
- _database-integrations/mongo/vanilla/v11-01-2016/mongodb-v11-01-2016.md
This PR releases MongoDB to GA. :tada:
> MongoDB/v1 - Release to GA

- _saas-integrations/marketo/marketo-latest.md
This commit was to mention the Bulk API extraction in the feature summary.
> Marketo/v1 - Add Bulk API to feature summary

- _data/taps/extraction/database-setup/user-privileges/dynamodb.yaml
- _database-integrations/dynamodb/dynamodb-v1.md
This PR adds the `getRecords` privilege to the Amazon DynamoDB docs.
> Amazon DynamoDB/v1 - Add getRecords privilege

- _database-integrations/mssql/amazon-rds/v1/microsoft-sql-server-amazon-rds-v1.md
- _database-integrations/mssql/azure/v1/microsoft-azure-v1.md
- _database-integrations/mssql/vanilla/v1/microsoft-sql-server-v1.md
added the log-based incremental notes for mssql database integration setups
> MSSQL/v1 - Add default replication method sections

- _database-integrations/oracle/oracle-rds/oracle-rds-v1.md
- _database-integrations/oracle/oracle-v1.md
This PR updates the Oracle docs to reflect the recent changes to SSL functionality.
> Update Oracle re: SSL

- _data/ui/database-integration-settings/dynamodb.yaml
- _data/ui/database-integration-settings/mongo.yml
- _data/ui/database-integration-settings/mssql.yml
- _data/ui/database-integration-settings/mysql.yml
- _data/ui/database-integration-settings/oracle.yml
- _data/ui/database-integration-settings/postgres.yml
- _data/ui/database-integration-settings/s3.yml
- _data/ui/database-integration-settings/sftp.yml
- _destinations/choosing-a-stitch-destination.md
- _includes/destinations/overviews/choosing-a-destination-rollup.html
- _includes/shared/database-connection-settings.html
- _includes/shared/incompatibilities/all-destination-incompatibility.html
This PR fixes a handful of bugs:
- Add `site.baseurl` to links in the Destination/Integration compatibility guide tables (DOC-814)
- Add a `Version` column to tables in the Choosing a Destination guide (DOC-843)
- Fix the display of Integration Settings fields for database integrations (DOC-845)
> Bug Fixes/3-4-2020

- _data/errors/extraction/saas/netsuite.yml
- _troubleshooting/errors/extraction-errors/saas/netsuite-suitetalk-extraction-errors.md
This PR adds a troubleshooting guide for NetSuite v1 extraction errors.
> NetSuite/v1 - Add extraction errors

- _saas-integrations/trello/trello-latest.md
Adds step regarding the "Allowed Origins" portion of the Trello App Key page
> Trello - Update Setup

- _integration-schemas/harvest-forecast/assignments.md
- _integration-schemas/harvest-forecast/foreign-keys.md
- _integration-schemas/harvest-forecast/people.md
- _integration-schemas/harvest-forecast/placeholders.md
- _integration-schemas/harvest-forecast/roles.md
- adds the `roles` and `placeholders` tables
> Harvest Forecast/v1 - Add roles and placeholders tables

- _data/taps/extraction/database-setup/user-privileges/mssql.yml
updates the `create-login-command` and `create-user-command` commands
> Azure MS SQL update commands

- _database-integrations/postgres/amazon-rds/v1/postgresql-amazon-rds-v1.md
this update mentions updating standby settings to avoid an error
> PostgreSQL RDS standby settings

- _saas-integrations/mambu/v1/mambu-v1.md
> Mambu/v1 - Correct certification status

- _saas-integrations/recharge/v1/recharge-v1.md
Corrects the certified status.
> Recharge/v1 - Update certification status

- _integration-schemas/shopify/abandoned_checkouts.md
- _integration-schemas/shopify/collects.md
- _integration-schemas/shopify/custom_collections.md
- _integration-schemas/shopify/customers.md
- _integration-schemas/shopify/metafields.md
- _integration-schemas/shopify/order_refunds.md
- _integration-schemas/shopify/orders.md
- _integration-schemas/shopify/products.md
- _integration-schemas/shopify/transactions.md
- _saas-integrations/shopify/v1/shopify-v1.md
Updates the API info to the July 2019 version.
> Shopify API Version Updates

- _account-security/security/encryption/encryption-general.md
- _account-security/security/encryption/reverse-ssh-tunnel-setup.md
- _account-security/security/stitch-security.md
- _data/sidebars/stitchnav.yml
- _data/stitch/subscription-plans/enterprise.yml
- _data/urls.yaml
This PR:
- Adds a guide for reverse SSH tunnels
- Adds info about data encryption at rest
> Reverse SSH Tunnels

- _saas-integrations/facebook-ads/facebook-ads-latest.md
> Facebook Ads - Update API

- _integration-schemas/bing-ads/v2/accounts.md
- _integration-schemas/bing-ads/v2/ad_groups.md
- _integration-schemas/bing-ads/v2/ad_performance_report.md
- _integration-schemas/bing-ads/v2/adgroup_performance_report.md
- _integration-schemas/bing-ads/v2/ads.md
- _integration-schemas/bing-ads/v2/age_gender_performance_report.md
- _integration-schemas/bing-ads/v2/campaign_performance_report.md
- _integration-schemas/bing-ads/v2/campaigns.md
- _integration-schemas/bing-ads/v2/geographic_performance_report.md
- _integration-schemas/bing-ads/v2/goals_and_funnels_report.md
- _integration-schemas/bing-ads/v2/keyword_performance_report.md
- _integration-schemas/bing-ads/v2/search_query_performance_report.md
- _saas-integrations/microsoft-advertising/v2/bing-ads-v2.md
Updates API and doc links to version 13
> Bing Ads - Update API and Doc Links

- _replication/replication-keys/syncing-historical-saas-data.md
> Historical Sync Typo

- _integration-schemas/hubspot/deal_pipelines.md
> Hubspot - Update deal_pipelines

- _database-integrations/mongo/mongodb-projection-queries.md
This adds to the "Projection query requirements for Stitch" section.
> MongoDB projection queries update

- _account-security/billing/billing-faq.md
Clarifies how mid-cycle plan changes works
> Billing - mid-cycle changes

- _data/ui/database-integration-settings/mssql.yml
This PR clarifies the behavior of the **Database** field for MSSQL integrations.
> MS SQL - Default DB explanation

- _data/errors/extraction/saas/google-sheets.yml
- _saas-integrations/google-sheets/v1/google-sheets-v1.md
This PR clarifies the requirements for header row values and updates the Extraction Error reference with the error/resolution for duplicate column names.
> Google Sheets/v1 - Unique header row values

- _integration-schemas/intercom/conversations.md
updates the possible values in the `type` subattribute for `conversations.conversation_message`.
> Intercom - conversation_message.type field values

- _getting-started/connecting-other-data-sources-guide.md
- changes "Stitch target" to "Singer target"
- changes the wording a little bit
> Update "How Singer taps work" section

- _saas-integrations/google-sheets/v1/google-sheets-v1.md
adds the data types in the replication section
> Google Sheets - data types section

- _layouts/coming-soon.html
- _saas-integrations/impact/v1/impact-v1.md
- _saas-integrations/mailshake/v1/mailshake-v1.md
This PR:
- Adds a `coming-soon` layout for integrations
- Adds Impact and Mailshake as coming soon
> Coming Soon for integrations - Add layout; Impact and Mailshake

- _data/connect/common/destination-forms.yaml
- _data/destinations/panoply/stitch-details.yml
- _developer-files/connect/api/objects/form-properties/destinations/amazon-s3-object.md
- _developer-files/connect/api/objects/form-properties/destinations/databricks-delta-object.md
- _developer-files/connect/api/objects/form-properties/destinations/dataworld-object.md
- _developer-files/connect/api/objects/form-properties/destinations/panoply-object.md
- _includes/developers/api-form-property-destination-fields.html
This PR:
- Updates the report card documentation for various destinations in the Connect API
- Adds Panoply to the Connect API
> Destination report card updates

- _data/taps/versions/google-sheets.yml
> Google Sheets/v1 - Update release status

- _integration-schemas/facebook-ads/ads_insights_age_and_gender.md
Updates the `ads_insights_age_and_gender` table. Corrects a `date-time` attribute to `string`.
> Facebook Ads update table

- _saas-integrations/kustomer/v1/kustomer-v1.md
I stumbled on this while working with a Support person
> Fix tap-kustomer to be community supported

- _data/connect/api.yml
This PR updates the URL for the Connect interest form.
> Update Connect interest form URL

- _saas-integrations/facebook-ads/facebook-ads-latest.md
Updates API from version 6.0 to version 8.0
> Facebook Ads update API

- _integration-schemas/frontapp/v1/tags_table.md
Adds `tags_table` table.
Note: There are several more new tables to add.
> Frontapp add tags table

- _integration-schemas/square/v1/payments.md
- adds the `cardholder_name` field to the `payments` table
> Square - add field

- _integration-schemas/asana/v2/projects.md
- _integration-schemas/asana/v2/tasks.md
- adds `start_on` field to the `tasks` table
- adds `custom_fields` to the `projects` table
> Asana - add fields

- _integration-schemas/saasoptics/v1/deleted_contracts.md
- _integration-schemas/saasoptics/v1/deleted_invoices.md
- _integration-schemas/saasoptics/v1/deleted_revenue_entries.md
- _integration-schemas/saasoptics/v1/deleted_transactions.md
- _integration-schemas/saasoptics/v1/foreign-keys.yml
- _integration-schemas/saasoptics/v1/invoices.md
- _integration-schemas/saasoptics/v1/revenue_entries.md
adds delete tables: transactions, invoices, revenue_entries, and contracts (https://github.com/singer-io/tap-saasoptics/pull/2), (https://github.com/singer-io/tap-saasoptics/pull/4)
> SaaSOptics - add delete tables

- _config.yml
- _data/sidebars/stitchnav.yml
- _replication/selecting-data/syncing-data.md
- _templates/integrations/databases/database-base.md
- _templates/integrations/saas/saas-base.md
This updates the templates for changes made in #561 and fixes a deploy issue for Netlify.
> Select All - Additional fixes

- sitemap.xml
Trying to fix the sitemap and search, again.
> Make URLs in sitemap explicit

- _saas-integrations/mixpanel/v1/mixpanel-v1.md
Removes step surrounding date_window_size config
> Mixpanel/v1 - Remove date_window_size step

- _saas-integrations/mixpanel/v1/mixpanel-v1.md
Reverts stitchdata/docs#572
I mistakenly merged this - we need to wait until the UI is actually addressed.
> Revert "Mixpanel/v1 - Remove date_window_size step"

- _integration-schemas/linkedin-ads/v1/ad_analytics_by_creative.md
> LinkedIn Ads/v1 - Update PK for ad_analytics_by_creative table

- _data-structure/nested-data-structures-row-count-impact.md
- _data/taps/extraction/data-types/postgres/v1.yml
Updates PostgreSQL specific note in nested data structures guide to correct data type handling.
Updates PostgreSQL specific data types JSON and JSONB to correct type handling.
> PostgreSQL/v1 - JSON and JSONB data type handling

- _data/urls.yaml
Fixes team member invite troubleshooting link.
> Broken Link - Account Troubleshooting

- _data/ui/common/database-connections.yml
- _data/ui/database-integration-settings/mongo.yml
- _data/ui/database-integration-settings/mssql.yml
- _data/ui/database-integration-settings/postgres.yml
Adds `Include Microsoft SQL Server schema names in destination tables (uncommon)` to the MS SQL docs.
> MS SQL - Server Schema sections

- _saas-integrations/square/v1/square-v1.md
Adds brief instructions for how to setup a sandbox environment integration for Square.
> Square/v1 - Add steps for sandbox setup

- _templates/integrations/saas/saas-coming-soon-page.md
This PR adds a template for the integration `Coming Soon` pages.
> Template - Coming Soon Page

- _developer-files/connect/api/objects/form-properties/sources/saas/pardot-object.md
- _saas-integrations/pardot/v1/pardot-v1.md
This updates the setup instructions for Pardot (v1) to reflect changes made to the integration. The integration now uses OAuth and the Pardot Business Unit ID to authenticate.
> Pardot - OAuth Setup

- _data/stitch/notifications/post-load-webhooks.yml
- _data/stitch/sdc-columns.yml
Updates the description of switch-views in the docs.
> Update description of version system columns

- _saas-integrations/mixpanel/v1/mixpanel-v1.md
Created an item in the requirements list.
> Mixpanel - US-based accounts only

- _account-security/billing/billing-faq.md
- _account-security/security/stitch-security.md
added the data retention policy to the billing > integration FAQs
> Security - add data retention policy

- _changelog/entries/2021/2021-03-19-google-analytics-v1-ltv-cohorts-docs.md
- _saas-integrations/google-analytics/v1/google-analytics-v1.md
Corrects the status of support for Lifetime Values and Cohorts.
> Google Analytics/v1 - Correct support status for LTV and Cohorts

- _data/taps/versions/intercom.yml
Adds deprecation and sunset date for Intercom (v02-02-2016).
> Intercom/v02-02-2016 - Add deprecation and sunset dates

- _integration-schemas/ebay/v1/orders.md
- _saas-integrations/ebay/v1/ebay-v1.md
Mentioned in the setup and and `orders` table to set a start date within 90 days.
> eBay - 90 historical window

- _database-integrations/dynamodb/dynamodb-v1.md
created a section about closing shards and how it can cause a replication delay
> DynamoDB - replication delays

- _changelog/entries/2016/2016-09-12-change-mongo-rep-keys.md
- _changelog/entries/2021/2021-06-01-postgres-v2-leaving-beta.md
- _changelog/entries/2021/2021-06-02-postgres-v2-leaving-beta.md
- _data/connect/common/database-sources.yml
- _data/errors/extraction/databases/postgres.yml
- _data/taps/extraction/data-types/postgres/specific.yml
- _data/taps/extraction/data-types/postgres/v2.yml
- _data/taps/versions/postgres.yml
- _database-integrations/postgres/vanilla/v2/postgres-v2.md
- _developer-content/connect/guides/api/source-destination-reference.md
- _developer-files/connect/api/documentation/api-form-properties.md
- _developer-files/connect/api/objects/form-properties/sources/databases/postgresql-object.md
- _developer-files/connect/api/objects/form-properties/sources/saas/marketo-object.md
- _replication/replication-methods/log-based-incremental-replication.md
- _troubleshooting/errors/extraction-errors/database-extraction-errors.md
- sass/_components.scss
- stylesheets/screen.css
This PR updates the docs to move PostgreSQL v2 from beta to GA.
> PostgreSQL/v2 - Leaving beta

- _changelog/entries/2021/2021-05-17-pendo-v1-anonymous-visitors.md
- _developer-files/connect/api/objects/form-properties/sources/saas/pendo-object.md
- _saas-integrations/pendo/v1/pendo-v1.md
This PR adds the new **Include Anonymous Visitors** setting to the Pendo docs. Documents this PR:  https://github.com/singer-io/tap-pendo/pull/32
> Pendo - anonymous visitors

- _changelog-files/2021/2021-07-14-stitch-js-deprecation.md
- _data/connect/core-objects/sessions.yml
- _data/connect/core-objects/streams.yml
- _developer-content/connect/connect-js.md
- _developer-content/developers.md
- _developer-files/connect/api/objects/sessions/create-a-session.md
- _includes/layout/top-page-notice.html
- _layouts/default.html
- sass/_components.scss
- sass/_mobile.scss
- stylesheets/screen.css
This PR deprecates the Stitch Connect JavaScript (Stitch.js) client.
> Stitch js deprecation

- _integration-schemas/facebook-ads/ads_insights_hourly_advertiser.md
Adds `ads_insights_hourly_advertiser` table.
> Facebook - add new hourly table

- index.md
This PR changes some minor formatting.
> Build Demo

- _account-security/settings/notifications/post-load-notifications.md
- _developer-content/post-load-webhooks/post-load-webhooks-reference.md
- _developer-files/connect/api/objects/notifications/notification-object.md
- _developer-files/connect/api/objects/notifications/post-load-hooks/create-hook-notification.md
- updates post-load webhooks pages
- updates Stitch Connect API Reference page post-load hook notification settings
> Post-Load Webhooks

- _changelog-files/2021/2021-08-19-get-import-api-access-tokens.md
- _developer-content/connect/guides/api/manage-import-api-access-tokens.md
includes the doc change and the changelog entry
> GET Import API acess tokens response

- _account-security/enterprise-features.md
- _data/stitch/subscription-plans/pro.yml
Fixes the pro plans features page
> Pro Plans Feature Tables

- _saas-integrations/crossbeam/v1/crossbeam-coming-soon.md
coming soon page for crossbeam
> Crossbeam Coming Soon

- _data/connect/common/database-sources.yml
- _database-integrations/mysql/vanilla/mysql-v2.md
- _developer-files/connect/api/objects/form-properties/sources/databases/amazon-aurora-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/google-cloudsql-mysql.md
- _developer-files/connect/api/objects/form-properties/sources/databases/hp-mysql-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/mariadb-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/mysql-object.md
> Revert "TDL-16557 updated doc for filter_dbs"

- _data/connect/common/database-sources.yml
- _database-integrations/mysql/vanilla/mysql-v2.md
- _developer-files/connect/api/objects/form-properties/sources/databases/amazon-aurora-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/google-cloudsql-mysql.md
- _developer-files/connect/api/objects/form-properties/sources/databases/hp-mysql-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/mariadb-object.md
- _developer-files/connect/api/objects/form-properties/sources/databases/mysql-object.md
> TDL-16557 updated doc for filter_dbs

- _data/dataloading/bigquery/object-names.yml
- _data/dataloading/databricks-delta/object-names.yml
- _data/dataloading/microsoft-sql-server/data-types.yml
- _data/dataloading/microsoft-sql-server/object-names.yml
- _data/dataloading/microsoft-sql-server/primary-keys.yml
- _data/dataloading/microsoft-sql-server/replication-keys.yml
- _data/dataloading/microsoft-sql-server/schema-changes.yml
- _data/dataloading/microsoft-sql-server/tables.yml
- _data/dataloading/microsoft-sql-server/warehouse-changes.yml
- _data/dataloading/scenarios/object-names.yml
- _data/dataloading/scenarios/primary-keys.yml
- _data/destinations/microsoft-sql-server/loading-errors.yml
- _data/sidebars/stitchnav.yml
- _destinations/microsoft-sql-server/microsoft-sql-server-category.md
- _replication/loading/data-loading-guides/microsoft-sql-server/microsoft-sql-server-data-loading-v1.md
- _templates/replication/data-loading/data-files/object-names.yml
- _templates/replication/data-loading/destination-data-loading.md
- _troubleshooting/errors/destination-loading-errors.md
> Microsoft SQL Server data loading and troubleshooting guides

- _includes/notifications/status-support/deprecated.html
Updates deprecated page to link deprecated version of different MySQL integrations to the latest HP MySQL version.
> TDL-16705 MySQL integrations deprecation

- _data/connect/api.yml
- _data/connect/core-objects/destinations.yml
- _data/connect/response-codes/destinations.yml
- _data/urls.yaml
- _database-integrations/database-integrations.md
- _destinations/choosing-a-stitch-destination.md
- _destinations/destination-integration-incompatibility.md
- _destinations/destinations.md
- _destinations/multiple-destinations.md
- _developer-content/connect/guides/api/create-configure-destination-connect-api.md
- _developer-files/connect/api/objects/destinations/v4/create-a-destination-v4.md
- _developer-files/connect/api/objects/destinations/v4/list-destinations-v4.md
- _developer-files/connect/api/objects/sources/create-a-source.md
- _developer-files/connect/api/objects/sources/update-a-source.md
- _getting-started/onboarding-guide.md
- _saas-integrations/integrations.md
- _saas-integrations/saas-integrations.md
- _webhook-integrations/webhook-integrations.md
- adds mapping keys for POST Source and POST Destination
- fixed sections that may have alluded to "one destination"
- adjusting multiple destination error codes
https://jira.talendforge.org/browse/TDL-16666
> Multiple Destinations - connect API mapping

- Gemfile.lock
- _saas-integrations/mixpanel/v1/mixpanel-v1.md
> Mixpanel - Hidden Fields

- _developer-files/connect/api/objects/notifications/post-load-hooks/create-hook-notification.md
> TDL-19166 Fixed request body

- _developer-files/connect/api/objects/form-properties/destinations/databricks-delta-object.md
> TDL-19105 fixed Databricks broken links

- _account-security/billing/billing-faq.md
adds the in-app bill/sold to and contact management details
> Manage Billing Details

- _integration-schemas/bing-ads/v2/age_gender_audience_report.md
- _integration-schemas/bing-ads/v2/goals_and_funnels_report.md
[TDL-17966](https://jira.talendforge.org/browse/TDL-17966)
- 
- 
> TDL-17966 Bing Ads required fields updates

- .github/workflows/changelog.yml
- scripts/changelog.py
> TDL-19465 added script and action to automate changelog entries

- .github/workflows/changelog.yml
> Changelog action testing

- _data/connect/api.yml
- _data/connect/general.yml
- _developer-content/connect/guides/api/create-configure-destination-connect-api.md
- _developer-files/connect/api/objects/destinations/v4/create-a-destination-v4.md
- _developer-files/connect/api/objects/destinations/v4/destination-object-v4.md
- _developer-files/connect/api/objects/destinations/v4/list-destinations-v4.md
- _developer-files/connect/api/objects/destinations/v4/update-a-destination-v4.md
> TDL-19106 Multi-destination updates in connect API

- _integration-schemas/klaviyo/campaigns.md
- _integration-schemas/klaviyo/clicked_sms.md
- _integration-schemas/klaviyo/consented_to_receive.md
- _integration-schemas/klaviyo/failed_to_deliver.md
- _integration-schemas/klaviyo/failed_to_deliver_automated_response.md
- _integration-schemas/klaviyo/received_automated_response.md
- _integration-schemas/klaviyo/received_sms.md
- _integration-schemas/klaviyo/sent_sms.md
> TDL-19332 klaviyo schema updates

- _integration-schemas/pipedrive/v1/deals.md
> TDL-19334 added new fields for pipedrive

- _data/taps/extraction/data-types/mysql/specific.yml
- _data/taps/extraction/data-types/mysql/v2.yml
- _database-integrations/mysql/vanilla/mysql-v2.md
> hp-mysql updates

- _integration-schemas/quickbooks/v1/profit_loss_report.md
> TDL-18459 New quickbooks schema

- _saas-integrations/google-ads/google-ads-latest.md
> TDL-19735 added missing doc about money fields

- _data/connect/api.yml
- _data/connect/common/destination-forms.yaml
- _data/connect/data-structures/details.yml
- _data/connect/response-codes/destinations.yml
- _developer-files/connect/api/objects/form-properties/destinations/microsoft-sql-server-object.md
- _developer-files/connect/api/objects/form-properties/destinations/mysql-object.md
- _developer-files/connect/api/objects/form-properties/destinations/postgresql-object.md
Documents:
- [TDL-19938](https://jira.talendforge.org/browse/TDL-19938)
- [TDL-19893](https://jira.talendforge.org/browse/TDL-19893)
- [TDL-19736](https://jira.talendforge.org/browse/TDL-19736)
- 
- 
> Connect API updates

- _saas-integrations/recharge/v1/recharge-v1.md
- _saas-integrations/recharge/v2/recharge-v2-coming-soon.md
> Recharge v2/Coming Soon page

- _data/destinations/databricks-delta/v1/data-types.yml
> Remove bigint from supported delta data-types

- _data/destinations/databricks-delta/v1/data-types.yml
> TDL-20480 Databricks Delta time range

- .github/workflows/changelog.yml
- scripts/changelog/changelog.py
- Added parameter for date range to GitHub Action
- Added monthly run
- 
- 
> TDL-20615 changelog script improvement

- _integration-schemas/hubspot/companies.md
- _integration-schemas/hubspot/deals.md
> TDL-20587 Hubspot stream updates

- scripts/changelog/changelog.py
> Fix changelog script

- _account-security/security/stitch-security.md
- _data/sidebars/stitchnav.yml
> TDL-20293 PII stored by Stitch

- _data/taps/extraction/data-types/mysql/v2.yml
> TDL-21045 Update destination type for JSON in MySQL

- _data/stitch/compliance.yml
- _data/taps/extraction/file-systems/file-requirements.yml
- _data/urls.yaml
> Removed references to HIPAA PDF

- _includes/youtube-player.html
- _saas-integrations/ga4/v1/ga4-v1.md
> GA4 Marketing Video

- _integration-schemas/dixa/v1/conversations.md
> TDL-21439 Dixa custom fields

- _data/taps/versions/intercom.yml
- _integration-schemas/intercom/v2/admins.md
- _integration-schemas/intercom/v2/companies.md
- _integration-schemas/intercom/v2/company_attributes.md
- _integration-schemas/intercom/v2/company_segments.md
- _integration-schemas/intercom/v2/contact_attributes.md
- _integration-schemas/intercom/v2/contacts.md
- _integration-schemas/intercom/v2/conversation_parts.md
- _integration-schemas/intercom/v2/conversations.md
- _integration-schemas/intercom/v2/foreign-keys.md
- _integration-schemas/intercom/v2/segments.md
- _integration-schemas/intercom/v2/tags.md
- _integration-schemas/intercom/v2/teams.md
- _saas-integrations/intercom/v2/intercom-v2.md
> TDL-20015 Intercom v2

- _integration-schemas/shopify/customers.md
- _integration-schemas/shopify/orders.md
- _saas-integrations/shopify/v1/shopify-v1.md
> TDL-21513 Shopify updates

- _saas-integrations/pipedrive/v1/pipedrive-v1.md
> Pipedrive certified

- _getting-started/free-trial.md
- _getting-started/getting-started-category.md
- _saas-integrations/github/v2/github-v2.md
- _saas-integrations/google-sheets/v2/google-sheets-v2.md
- _saas-integrations/klaviyo/v1/klaviyo-v1.md
- _saas-integrations/microsoft-advertising/v2/bing-ads-v2.md
- index.md
Add to the bottom of:
Klaviyo, Google Sheets, Bing Ads, GitHub
Add to:
Home page, getting started, free trial pages
> Add promo video to certain pages

- _saas-integrations/jira/v2/jira-v2.md
> JIRA: add unsupported locales

- _data/taps/versions/linkedin-ads.yml
- _includes/integrations/saas/attribution-windows.html
- _integration-schemas/linkedin-ads/v2/account_users.md
- _integration-schemas/linkedin-ads/v2/accounts.md
- _integration-schemas/linkedin-ads/v2/ad_analytics_by_campaign.md
- _integration-schemas/linkedin-ads/v2/ad_analytics_by_creative.md
- _integration-schemas/linkedin-ads/v2/campaign_groups.md
- _integration-schemas/linkedin-ads/v2/campaigns.md
- _integration-schemas/linkedin-ads/v2/creatives.md
- _integration-schemas/linkedin-ads/v2/foreign-keys.md
- _integration-schemas/linkedin-ads/v2/video_ads.md
- _saas-integrations/linkedin-ads/v1/linkedin-ads-v1.md
- _saas-integrations/linkedin-ads/v2/linkedin-ads-v2.md
> TDL-21883 LinkedIn Ads v2

- _saas-integrations/tiktok-ads/tiktok-ads-v1-coming-soon-page.md
> TDL-21847 TikTok Ads coming soon page

- _integration-schemas/helpscout/v1/conversations.md
- _integration-schemas/helpscout/v1/customers.md
- _integration-schemas/helpscout/v1/happiness_ratings_report.md
- _integration-schemas/helpscout/v1/team_members.md
- _integration-schemas/helpscout/v1/teams.md
- _saas-integrations/helpscout/helpscout-v1.md
> TDL-21953 Help Scout updates

- _changelog-files/2023/2023-02-16-hubspot-v2-tickets-stream.md
- _integration-schemas/hubspot/tickets.md
> Hubspot tickets stream

- _saas-integrations/mambu/v2/mambu-v2.md
- _saas-integrations/mambu/v4/mambu-coming-soon-page.md
> Mambu v4 "Coming Soon" page

- _data/taps/versions/sailthru.yml
- _integration-schemas/sailthru/blast_query.md
- _integration-schemas/sailthru/v1/ad_targeter_plans.md
- _integration-schemas/sailthru/v1/blast_repeats.md
- _integration-schemas/sailthru/v1/blast_save_list.md
- _integration-schemas/sailthru/v1/blasts.md
- _integration-schemas/sailthru/v1/foreign-keys.md
- _integration-schemas/sailthru/v1/lists.md
- _integration-schemas/sailthru/v1/purchase_log.md
- _integration-schemas/sailthru/v1/users.md
- _saas-integrations/sailthru/v1/sailthru-v0.2.md
> Sailthru v1 - update table schema

- _changelog-files/2022/2022-05-09-google-ads-v1-implement-automatic-keys.md
- _replication/loading/pipeline-monitoring.md
> accross => across

- _saas-integrations/twilio/v1/twilio-coming-soon-page.md
> Twilio Coming Soon Page

- _database-integrations/mongo/mongo-atlas/v2/mongodb-atlas-v2.md
- _database-integrations/mongo/vanilla/v2/mongodb-v2.md
> TDL-22346 Update supported MongoDB versions

- _account-security/security/sso/azure-active-directory-single-sign-on-guide.md
- _account-security/security/sso/google-workspace-single-sign-on-guide.md
- _account-security/security/sso/okta-single-sign-on-guide.md
- _account-security/security/sso/onelogin-single-sign-on-guide.md
- _account-security/security/sso/pingfederate-single-sign-on-guide.md
- _account-security/settings/managing-team-members.md
> TDL-21186 Remove mentions of SSO Admin

- _database-integrations/mssql/amazon-rds/v1/microsoft-sql-server-amazon-rds-v1.md
- _database-integrations/mssql/azure/v1/microsoft-azure-v1.md
- _database-integrations/mssql/vanilla/v1/microsoft-sql-server-v1.md
> TDL-21943 MSSQL Primary Key requirement

- _data/taps/versions/google-search-console.yml
- _integration-schemas/google-search-console/v1/performance_report_country.md
- _integration-schemas/google-search-console/v1/performance_report_custom.md
- _integration-schemas/google-search-console/v1/performance_report_date.md
- _integration-schemas/google-search-console/v1/performance_report_device.md
- _integration-schemas/google-search-console/v1/performance_report_page.md
- _integration-schemas/google-search-console/v1/performance_report_query.md
> TDL-22658 Google Search Console GA

- _saas-integrations/mambu/v2/mambu-v2.md
> Remove Mambu v2 from TOC

- _destinations/multiple-destinations.md
> TDL-23284 Fix for multiple destinations docs

- _integration-schemas/zendesk/v2/talk_phone_numbers.md
- _integration-schemas/zendesk/v2/ticket_metric_events.md
> TDL-23171 New Zendesk streams

- _developer-content/connect/guides/api/source-destination-reference.md
Replace duplicate "Update a destination" with "Update a source" in source-destination-reference.
> Add "Update a source"

- _changelog-files/2023/2023-07-27-mongodb-v3.md
- _data/taps/extraction/data-types/mongodb/v3.yml
- _data/taps/versions/mongodb.yml
- _database-integrations/mongo/mongo-atlas/v3/mongodb-atlas-v3.md
- _database-integrations/mongo/vanilla/v3/mongodb-v3.md
> TDL-23698 MongoDB v3

- _integration-schemas/pendo/v1/page_events.md
- _saas-integrations/pendo/v1/pendo-v1.md
> TDL-23735 Pendo updates

- _integration-schemas/tiktok-ads/ad_insights.md
- _integration-schemas/tiktok-ads/ad_insights_by_country.md
- _integration-schemas/tiktok-ads/ad_insights_by_platform.md
- _integration-schemas/tiktok-ads/adgroups.md
- _integration-schemas/tiktok-ads/ads.md
- _integration-schemas/tiktok-ads/advertisers.md
- _integration-schemas/tiktok-ads/campaigns.md
- _integration-schemas/tiktok-ads/v1/ad_insights.md
- _integration-schemas/tiktok-ads/v1/ad_insights_by_age_and_gender.md
- _integration-schemas/tiktok-ads/v1/ad_insights_by_country.md
- _integration-schemas/tiktok-ads/v1/ad_insights_by_platform.md
- _integration-schemas/tiktok-ads/v1/adgroups.md
- _integration-schemas/tiktok-ads/v1/ads.md
- _integration-schemas/tiktok-ads/v1/advertisers.md
- _integration-schemas/tiktok-ads/v1/campaign_insights_by_province.md
- _integration-schemas/tiktok-ads/v1/campaigns.md
- _saas-integrations/tiktok-ads/tiktok-ads-v1.md
> TikTok Ads/v1 - include deleted feature

- _config.yml
- _database-integrations/database-integrations.md
- _includes/integrations/templates/integration-category-tiles.html
- _saas-integrations/integrations.md
- _saas-integrations/saas-integrations.md
- _webhook-integrations/webhook-integrations.md
> TDL-23755 Remove references to Singer roadmap

- _account-security/security/sso/single-sign-on.md
- _account-security/settings/change-email-address-password.md
- _data/stitch/user-management/roles/general-user.yml
- _data/taps/extraction/netsuite/netsuite-permissions.yml
- _replication/extraction-tab/integration-extraction-logs.md
- _saas-integrations/connection-cloning.md
> TDL-23953 Netsuite permissions

- _integration-schemas/facebook-ads/ads_insights.md
- _integration-schemas/facebook-ads/ads_insights_age_and_gender.md
- _integration-schemas/facebook-ads/ads_insights_country.md
- _integration-schemas/facebook-ads/ads_insights_dma.md
- _integration-schemas/facebook-ads/ads_insights_platform_and_device.md
- _integration-schemas/facebook-ads/ads_insights_region.md
> TDL-23940 - Facebook Ads: Add conversions to insights streams

- _saas-integrations/hubspot/v2/hubspot-v2.md
- _saas-integrations/zoom/v2/zoom-v2.md
> TDL-22720 Add steps for Zoom integration removal

- _changelog-files/2023/2023-09-22-amazon-s3-csv-v1-jsonl-support.md
- _data/taps/extraction/file-systems/file-requirements.yml
- _database-integrations/amazon-s3/amazon-s3-csv-latest.md
- _includes/integrations/shared-setup/configure-table-settings-file-server.html
> TDL-23919 S3 JSONL support

- _includes/integrations/templates/schemas/schemas.html
> Sort integration tables alphabetically

- _data/taps/schemas/asana/v2/asana-v2-issues.txt
- _data/taps/schemas/asana/v2/asana-v2-tables.yml
- _data/taps/schemas/asana/v2/json/subtasks.json
> [tap-asana] Schema updates

- _troubleshooting/integrations/disabled-sessions-mongodb.md
> MongoDB sessions

- _data/taps/schemas/mambu/v4/mambu-v4-tables.yml
> Tdl 25066 client stream mambu

- _data/taps/versions/netsuite.yml
> Fixed Netsuite version

- _saas-integrations/netsuite/v2/netsuite-v2.md
> Netsuite file Singer update

- _saas-integrations/salesforce/salesforce-latest/salesforce-latest.md
- _saas-integrations/salesforce/v2/salesforce-v2.md
> TDL-24111 Fixed link

- _saas-integrations/twitter-ads/v1/twitter-ads-v1.md
https://jira.talendforge.org/browse/TDL-17972 
- 
- 
> TDL-17972 Upgraded API version

- _saas-integrations/xero/xero-latest.md
https://jira.talendforge.org/browse/DOCT-19646
- 
- 
> DOCT-19646 Added SSO requirement for Xero

- index.md
> removed youtube video

- _saas-integrations/google-sheets/v3/google-sheets-v3.md
> Added info in the prereqs of Google Sheets

- _data/sidebars/stitchnav.yml
> Nav Analytics tools

- _data/taps/versions/google-sheets.yml
> Fixed Google Sheets V3

- _layouts/default.html
Remove the Intercom chat thing
Run it and see if there is only one chat bot in the lower right corner.
Some JavaScript error maybe?
> HELPELSA-3415: Remove the Intercom bubble

- _saas-integrations/google-ads/google-ads-latest.md
> Google Ads API version

- _saas-integrations/google-ads-adwords/google-ads-adwords-latest.md
> Test publication

- _includes/layout/head.html
- _layouts/default.html
Adding subresource integrity checks for cloudflare URLs
- Check that the html loads correctly in the browser and there aren't any integrity errors in the console
- Docs page might not display properly if a mistake was made
> Adding subresource integrity checks for cloudflare URLs

- CONTRIBUTING.md
- README.md
- _config.yml
- _data/stitch/compliance.yml
- _data/taps/features.yml
- _database-integrations/database-integrations.md
- _destinations/destinations.md
- _developer-files/connect/guides/connect-guides-feedback.md
- _developer-files/import-api/guides/import-api-guides-feedback.md
- _developer-files/import-api/overview/iapi-overview-libraries.md
- _includes/layout/feedback.html
- _includes/notifications/status-support/support.html
- _includes/replication/replication-stats-copy.html
- _replication/selecting-data/syncing-data.md
- _saas-integrations/saas-integrations.md
- _troubleshooting/data-discrepancies/data-discrepancy-troubleshooting-guide.md
- _troubleshooting/destinations/databricks-delta-issues.md
- _troubleshooting/destinations/panoply-issues.md
- _troubleshooting/replication/missing-tables-and-columns.md
> Updated support contact

- _data/taps/versions/heroku.yml
> Heroku - Fix wrong link

- _data/taps/schemas/shopify/v2/json/abandoned_checkouts.json
- _data/taps/schemas/shopify/v2/json/collects.json
- _data/taps/schemas/shopify/v2/json/custom_collections.json
- _data/taps/schemas/shopify/v2/json/customers.json
- _data/taps/schemas/shopify/v2/json/events.json
- _data/taps/schemas/shopify/v2/json/inventory_items.json
- _data/taps/schemas/shopify/v2/json/inventory_levels.json
- _data/taps/schemas/shopify/v2/json/locations.json
- _data/taps/schemas/shopify/v2/json/metafields.json
- _data/taps/schemas/shopify/v2/json/order_refunds.json
- _data/taps/schemas/shopify/v2/json/orders.json
- _data/taps/schemas/shopify/v2/json/product_variants.json
- _data/taps/schemas/shopify/v2/json/products.json
- _data/taps/schemas/shopify/v2/json/transactions.json
- _data/taps/schemas/shopify/v2/shopify-v2-foreign-keys.yml
- _data/taps/schemas/shopify/v2/shopify-v2-tables.yml
- _data/taps/versions/shopify.yml
- _saas-integrations/shopify/v1/shopify-v1.md
- _saas-integrations/shopify/v2/shopify-v2.md
> Shopify v2

- _saas-integrations/twitter-ads/v1/twitter-ads-v1.md
> Keywords for X (Twitter Ads)

- _data/taps/schemas/square/v2/square-v2-tables.yml
> updated replication method and keys
